### eval testing

## import lib & var setting

In [ ]:
# Import Pytorch
import torch
from torch import nn

# Import torchvision
import torchvision
from torchvision import datasets
from torchvision import transforms
from torchvision.transforms import ToTensor

# Import matplotlib for visulization
import matplotlib.pyplot as plt

import sys 

import cv2

import pandas as pd  # 資料分析套件
import numpy as np
import os
from time import time
import re

In [ ]:
# ===== var setting   ========

# csv_file = '../data/img_feature.csv'
# csv_file = '../data/img_feature_no_masked.csv'
csv_file = '../data/img_conv2.csv'
# random_seed = 42
# dataset_path = "../HAM10000/base_img_data/"
dataset_path = "../HAM10000/images/"
groundtruth_file = '../HAM10000/GroundTruth.csv'

## prepocessing train & test data

### create name to label dict

In [ ]:
# 读取 CSV 文件
# groundtruth_data = pd.read_csv(groundtruth_file)


In [ ]:
# groundtruth_data.head()
# import pandas as pd

# # 假設 df 是您的 DataFrame
# # df = pd.DataFrame(...)

# def find_indices_of_ones(row):
#     # 尋找前六個元素中 1 的位置
#     return [(i-1) for i, x in enumerate(row[:8]) if x == 1]

# # 將函數應用於每行並創建新列 'label'
# groundtruth_data['label'] = groundtruth_data.apply(find_indices_of_ones, axis=1)

# # groundtruth_data.head()

# # find ele == 1
# filename_to_label_dict = groundtruth_data.set_index('image')['label'].to_dict()

# # {'1234' : [2] ,'1235' : [3] } -> {'1234' : 2 ,'1235' : 3 }
# filename_to_label_dict =  {key: value[0] if value else None for key, value in filename_to_label_dict.items()}

# type(filename_to_label_dict['ISIC_0024306'])

# # {'1234' : 2 ,'1235' : 3 } -> {'1234.jpg' : 2 ,'1235.jpg' : 3 }
# filename_to_label_dict =  {key + ".jpg": value for key, value in filename_to_label_dict.items()}




# # check if value is out of range
# null_keys = [key for key, value in filename_to_label_dict.items() if value is None]


# all_values_in_range = all(0 <= value <= 6 for value in filename_to_label_dict.values())

# # 輸出結果
# print("所有的值都在範圍內：" if all_values_in_range else "有些值不在範圍內。")

### 分出train 跟test的data loader

In [ ]:
import random
import os
import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from helperFunction.CustomImageDataset import CustomImageDataset 

# # 假設您的圖片和標籤字典如下
# img_dir = dataset_path

# # list all filename from file
# all_files = [f for f in os.listdir(dataset_path) if os.path.isfile(os.path.join(dataset_path, f))]

# # list all filename from dict
# # all_files = list(filename_to_label_dict.keys())

# random.seed(42)

# num_total_samples = len(all_files)
# split_ratio = 0.8  # 80% 的数据用于训练，20% 用于测试

# # 随机打乱数据集
# random.shuffle(all_files)

# # 计算分割点
# split_idx = int(num_total_samples * split_ratio)

# # 分割数据集
# train_files = all_files[:split_idx]
# test_files = all_files[split_idx:]

gray_mean = sum([0.485, 0.456, 0.406]) / 3
gray_std = sum([0.229, 0.224, 0.225]) / 3


# 可以加入轉換
transform64 = torchvision.transforms.Compose([
    transforms.Resize(size=(64,64)),
    torchvision.transforms.ToTensor()
    # 其他轉換
])

transform_std = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

transform_gray_single_channel = transforms.Compose([
    transforms.Resize(256),  # 调整图像大小至256x256
    transforms.CenterCrop(224),  # 中心裁剪至224x224
    transforms.Grayscale(),  # 将图像转换为灰度图
    transforms.ToTensor(),  # 转换为Tensor
    # 归一化，均值和标准差应根据灰度图的实际分布进行调整
    # 这里使用ImageNet预训练模型的均值和标准差的平均值作为示例
    transforms.Normalize(mean=[0.449], std=[0.226]),
])

transform_gray_pretrain_fit = transforms.Compose([
    # transforms.Grayscale(num_output_channels=1),  # 将图像转换为单通道灰度图像
    # transforms.Lambda(lambda x: x.repeat(3, 1, 1)),  # 复制灰度通道到三个通道
    # 其他需要的转换，如 Resize, Normalize 等
    transforms.Resize(256),  # 例如，调整图像大小
    transforms.CenterCrop(224),  # 中心裁剪
    transforms.ToTensor(),  # 转换为Tensor
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),  # 归一化
])

transform_gray_CT_img_fit = transforms.Compose([
    # transforms.Grayscale(num_output_channels=1),  # 将图像转换为单通道灰度图像
    # transforms.Lambda(lambda x: x.repeat(3, 1, 1)),  # 复制灰度通道到三个通道
    # 其他需要的转换，如 Resize, Normalize 等
    transforms.Resize(256),  # 例如，调整图像大小
    transforms.CenterCrop(224),  # 中心裁剪
    transforms.ToTensor(),  # 转换为Tensor
    transforms.Normalize(mean=[gray_mean,gray_mean,gray_mean], std=[gray_std,gray_std,gray_std]),  # 归一化
])





# transform224_gray_32bit =  transforms.Compose([
#     transforms.Lambda(lambda img: np.array(img).astype(np.float32) / 255.0),  # 将PIL Image转换为NumPy数组，并更改数据类型
#     transforms.Lambda(lambda x: torch.from_numpy(x)),  # 将NumPy数组转换为Tensor
#     transforms.Resize(256),  # 调整图像大小
#     transforms.CenterCrop(224),  # 中心裁剪到224x224
#     # transforms.Lambda(lambda x: x.unsqueeze(0)),  # 增加一个通道维度
#     transforms.Normalize(mean=[0.485], std=[0.229]),  # 使用单个值的均值和标准差进行归一化
# ])



# # 创建训练集和测试集的数据加载器
# train_dataset_64 = CustomImageDataset(img_dir=img_dir, file_to_label_dict={file: filename_to_label_dict[file] for file in train_files}, transform=transform64)
# test_dataset_64 = CustomImageDataset(img_dir=img_dir, file_to_label_dict={file: filename_to_label_dict[file] for file in test_files}, transform=transform64)

# # 创建数据加载器
# train_data_loader_64 = DataLoader(train_dataset_64, batch_size=32, shuffle=True)
# test_data_loader_64 = DataLoader(test_dataset_64, batch_size=32, shuffle=False)


# # 创建训练集和测试集的数据加载器
# train_dataset_224 = CustomImageDataset(img_dir=img_dir, file_to_label_dict={file: filename_to_label_dict[file] for file in train_files}, transform=transform224)
# test_dataset_224 = CustomImageDataset(img_dir=img_dir, file_to_label_dict={file: filename_to_label_dict[file] for file in test_files}, transform=transform224)

# # 创建数据加载器
# train_data_loader_224 = DataLoader(train_dataset_224, batch_size=32, shuffle=True)
# test_data_loader_224 = DataLoader(test_dataset_224, batch_size=32, shuffle=False)

# # 創建 Dataset 和 DataLoader
# dataset = CustomImageDataset(img_dir=img_dir, file_to_label_dict=filename_to_label_dict, transform=transform)
# data_loader = DataLoader(dataset, batch_size=32, shuffle=True)

# # 使用 DataLoader
# for images, labels in data_loader:
#     # 這裡進行訓練過程
#     pass

In [ ]:
# @transform test unit

# image = Image.open('../data/chestCTData/images/train/adenocarcinoma/000000 (6).png')

# # 打印图像的格式
# print("Format:", image.format)

# # 打印图像的尺寸
# print("Size:", image.size)

# # 打印图像的模式
# print("Mode:", image.mode)

# # 打印图像的额外信息（如果有的话）
# print("Info:", image.info)

# # 将图像转换为NumPy数组
# image_array = np.array(image)

# # 打印图像数组的形状和部分像素值
# print("Image shape:", image_array.shape)
# print("Some pixel values:", image_array[100:110, 100:110])  # 打印左上角5x5区域的像素值

# transformed_img = transform_gray(image)

# print(transformed_img.shape)

In [ ]:
sys.path.append(os.path.abspath('..'))

from data.chestCTData.chestCTDataloader import ChestCTDataProcessor
from data.HAM10000.ham10000Dataloader import HAM10000DataProcessor

dataContainer = ChestCTDataProcessor(transform=transform_std)
# dataContainer = HAM10000DataProcessor(transform=transform_std)

model_folder_path = '../model/CT chest'
# model_folder_path = '../model/HAM10000'


train_dataloader , test_dataloader = dataContainer.returnDataloaders()


# dataContainer.dataPreprocess()

Classes: ['adenocarcinoma', 'large.cell.carcinoma', 'normal', 'squamous.cell.carcinoma']
Class to index: {'adenocarcinoma': 0, 'large.cell.carcinoma': 1, 'normal': 2, 'squamous.cell.carcinoma': 3}
Samples: [('c:\\Users\\E\\Desktop\\skin_cancer_dataset\\data\\chestCTData\\images\\test\\adenocarcinoma\\000108 (3).png', 0), ('c:\\Users\\E\\Desktop\\skin_cancer_dataset\\data\\chestCTData\\images\\test\\adenocarcinoma\\000109 (2).png', 0), ('c:\\Users\\E\\Desktop\\skin_cancer_dataset\\data\\chestCTData\\images\\test\\adenocarcinoma\\000109 (4).png', 0), ('c:\\Users\\E\\Desktop\\skin_cancer_dataset\\data\\chestCTData\\images\\test\\adenocarcinoma\\000109 (5).png', 0), ('c:\\Users\\E\\Desktop\\skin_cancer_dataset\\data\\chestCTData\\images\\test\\adenocarcinoma\\000112 (2).png', 0)]
First image size: torch.Size([3, 224, 224])
First image label: 0


In [ ]:
img, label = next(iter(train_dataloader))

# Batch size will now be 1, you can cahnge the batch size if you like
print(f"Image shape: {img.shape} -> [batch_size, color_channels, height, width]")
print(f"Label shape: {label.shape}") # equal to batch siz

Image shape: torch.Size([32, 3, 224, 224]) -> [batch_size, color_channels, height, width]
Label shape: torch.Size([32])


In [ ]:
# 儲存file list的資訊給XGB訓練時使用
# import json
# with open('test_files_list.json', 'w') as f:
#     json.dump(test_files, f)
# with open('train_files_list.json', 'w') as f:
#     json.dump(train_files, f)

## Bulid TinyVGG model

In [ ]:
# from custom_model.TinyVGG import TinyVGG

# model_0 = TinyVGG(input_shape=3,
#                   hidden_units=10,
#                   output_shape=7)
# model_0

In [ ]:
# forward testing

# print(model_0(img))

In [ ]:
# from torchinfo import summary
# summary(model_0, input_size=[1,3,64,64])


In [ ]:
import torch
# Setup device-agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Build VGG16 model

In [ ]:
# import torch
# import torch.nn as nn

# class VGG16(nn.Module):
#     def __init__(self, num_classes=1000):
#         super(VGG16, self).__init__()
        
#         # 定义 VGG16 的卷积层部分
#         self.features = nn.Sequential(
#             nn.Conv2d(3, 64, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(64, 64, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.MaxPool2d(kernel_size=2, stride=2),
            
#             nn.Conv2d(64, 128, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(128, 128, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.MaxPool2d(kernel_size=2, stride=2),
            
#             nn.Conv2d(128, 256, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(256, 256, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(256, 256, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.MaxPool2d(kernel_size=2, stride=2),
            
#             nn.Conv2d(256, 512, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(512, 512, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(512, 512, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.MaxPool2d(kernel_size=2, stride=2),
            
#             nn.Conv2d(512, 512, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(512, 512, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(512, 512, kernel_size=3, padding=1),
#             nn.ReLU(inplace=True),
#             nn.MaxPool2d(kernel_size=2, stride=2),
#         )

#         # 定义 VGG16 的全连接层部分
#         self.classifier = nn.Sequential(
#             nn.Linear(512 * 7 * 7, 4096),
#             nn.ReLU(inplace=True),
#             nn.Dropout(),
#             nn.Linear(4096, 4096),
#             nn.ReLU(inplace=True),
#             nn.Dropout(),
#             nn.Linear(4096, num_classes),
#         )

#     def forward(self, x):
#         # 通过卷积层
#         x = self.features(x)
        
#         # 展平操作
#         x = x.view(x.size(0), -1)
        
#         # 通过全连接层
#         x = self.classifier(x)
        
#         return x

# model_vgg16 = VGG16(num_classes=7)

In [ ]:
# from torchinfo import summary
# summary(model_vgg16, input_size=[1,3,224,224])


## Train & test function defination

In [ ]:
# Cteate train_step()
def train_step(model: torch.nn.Module,
        dataloader: torch.utils.data.DataLoader,
        loss_fn: torch.nn.Module,
        optimizer: torch.optim.Optimizer,
        device=device):
  # Put the model in train mode
  model.train()

  # Setup train loss and train accuracy values
  train_loss, train_acc = 0, 0

  # Loop thourgh data loader data batches
  for batch,(X, y) in enumerate(dataloader):
    # Send data to the target device
    X, y = X.to(device) , y.to(device)

    # 1. Forward pass
    y_pred = model(X)

    # 2. Calculate the loss
    loss = loss_fn(y_pred, y)
    train_loss += loss.item()

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Loss backward
    loss.backward()

    # 5 Optimizer step
    optimizer.step()

    # Calculat accuracy metric
    y_pred_class = torch.argmax(torch.softmax(y_pred, dim=1), dim=1)
    train_acc += (y_pred_class==y).sum().item()/len(y_pred)

  # Adjust metrics to get average loss and accuracy per batch
  train_loss = train_loss / len(dataloader)
  train_acc = train_acc / len(dataloader)
  return train_loss, train_acc

In [ ]:
from sklearn.metrics import f1_score
# Create a test step
def test_step(model: torch.nn.Module,
        dataloader: torch.utils.data.DataLoader,
        loss_fn: torch.nn.Module,
        device=device):
  # Put the model in eval mode
  model.eval()

  # Setup test loss and test accuracy values
  test_loss, test_acc, all_preds, all_labels = 0, 0, [], []

  with torch.inference_mode():
    # Loop thourgh data loader data batches
    for batch,(X, y) in enumerate(dataloader):
      # Send data to the target device
      X, y = X.to(device) , y.to(device)

      # 1. Forward pass
      test_pred_logits = model(X)

      # 2. Calculate the loss
      loss = loss_fn(test_pred_logits, y)
      test_loss += loss.item()


      # Calculate accuracy
      test_pred_labels = test_pred_logits.argmax(dim=1) # Maybe same as softmax results?
      test_acc += (test_pred_labels==y).sum().item() / len(test_pred_labels)

      all_preds.extend(test_pred_labels.cpu().numpy())
      all_labels.extend(y.cpu().numpy())

  # Adjust metrics to get average loss and accuracy per batch
  test_loss = test_loss / len(dataloader)
  test_acc = test_acc / len(dataloader)
  # cal F1 score
  f1 = f1_score(all_labels, all_preds, average='weighted')

  return test_loss, test_acc, f1

In [ ]:
from tqdm.auto import tqdm

# 1. Create a train function that takes in various model parameters + optimizer + dataloader + loss functoin
def train(model: torch.nn.Module,
          train_dataloader: torch.utils.data.DataLoader,
          test_dataloader: torch.utils.data.DataLoader,
          optimizer: torch.optim.Optimizer,
          loss_fn: torch.nn.Module = nn.CrossEntropyLoss(),
          epochs: int = 5,
          best_model_name: str = "best_model.pth",
          device=device,
          enable_early_stop=True):
  # 2. Create empty results dicitonary
  results = {"train_loss": [],
        "train_acc":[],
        "test_loss": [],
        "test_acc":[]}
  
  # init best model loss var
  best_test_loss = float('inf')
  best_model = None
  early_stop_count = 0
  early_stop_limit = 7

  # 3. Loop through training and testing steps for a number of epochs
  for epoch in tqdm(range(epochs)):
    train_loss, train_acc = train_step(model=model,
                        dataloader=train_dataloader,
                        loss_fn=loss_fn,
                        optimizer=optimizer,
                        device=device)
    test_loss, test_acc, test_f1 = test_step(model=model,
                      dataloader=test_dataloader,
                      loss_fn=loss_fn,
                      device=device)
    # 4. Print out what's happening
    print(f"Epoch: {epoch} | Train loss: {train_loss:.4f} | Train acc: {train_acc:.4f} | Test loss: {test_loss:.4f} | Test acc: {test_acc:.4f} |  F1 score: {test_f1:.4f}   ")

    # 5. Update results dictionary
    results["train_loss"].append(train_loss)
    results["train_acc"].append(train_acc)
    results["test_loss"].append(test_loss)
    results["test_acc"].append(test_acc)

    if test_loss < best_test_loss:
      best_test_loss = test_loss
      best_test_acc = test_acc
      best_test_f1 = test_f1
      # best_model = model.state_dict()
      torch.save(model.state_dict(), best_model_name)
      early_stop_count = 0
    else:
      if enable_early_stop:
        early_stop_count += 1
    
    if early_stop_count >= early_stop_limit:
      print("Early stopping triggered.")
      break

  # 6. Return the filled results at the end of the eopchs
      
  # save best model
  # torch.save(best_model, best_model_name)
  print("the best test acc is :{:.4f}".format(best_test_acc))
  print("the best F1 score is :{:.4f}".format(best_test_f1))
  return results

c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
from helperFunction.TrainHelper import TrainingHelper

num_CT_classes = 4
num_skin_classes = 7

num_classes = num_skin_classes

# Train model

## VGG

load preTrained VGG16, num_class = 1000

In [ ]:
import torchvision.models as models

model_preTrained_VGG16 = models.vgg16(pretrained=True).to(device)     # 使用內建的 model 

optimizer = torch.optim.SGD(model_preTrained_VGG16.parameters(), lr = 0.001) # 選擇你想用的 optimizer
# optimizer = torch.optim.Adam(model_VGG16.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 

# Start the timer
from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG_results = train(model=model_preTrained_VGG16,
              train_dataloader=train_dataloader,
              test_dataloader=test_dataloader,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name= model_folder_path + "/best_model_pretrain_VGG16.pth",
              epochs=40)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")

c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  0%|          | 0/40 [00:00<?, ?it/s]

Epoch: 0 | Train loss: 3.1632 | Train acc: 0.3028 | Test loss: 1.3673 | Test acc: 0.4921 |  F1 score: 0.4772   


  2%|▎         | 1/40 [00:16<10:43, 16.51s/it]

Epoch: 1 | Train loss: 1.2012 | Train acc: 0.5963 | Test loss: 1.0539 | Test acc: 0.5698 |  F1 score: 0.5563   


  5%|▌         | 2/40 [00:28<08:53, 14.03s/it]

Epoch: 2 | Train loss: 0.8656 | Train acc: 0.6750 | Test loss: 0.9513 | Test acc: 0.5681 |  F1 score: 0.5541   


 10%|█         | 4/40 [00:51<07:20, 12.23s/it]

Epoch: 3 | Train loss: 0.7793 | Train acc: 0.6981 | Test loss: 3.1282 | Test acc: 0.2466 |  F1 score: 0.1630   


 12%|█▎        | 5/40 [01:02<06:50, 11.72s/it]

Epoch: 4 | Train loss: 0.7704 | Train acc: 0.7369 | Test loss: 1.0096 | Test acc: 0.5786 |  F1 score: 0.5484   
Epoch: 5 | Train loss: 0.5149 | Train acc: 0.8063 | Test loss: 0.8682 | Test acc: 0.6220 |  F1 score: 0.6045   


 18%|█▊        | 7/40 [01:25<06:23, 11.62s/it]

Epoch: 6 | Train loss: 0.4543 | Train acc: 0.8238 | Test loss: 1.5038 | Test acc: 0.5638 |  F1 score: 0.4828   
Epoch: 7 | Train loss: 0.4121 | Train acc: 0.8672 | Test loss: 0.8676 | Test acc: 0.6448 |  F1 score: 0.6195   


 20%|██        | 8/40 [01:38<06:20, 11.90s/it]

Epoch: 8 | Train loss: 0.3451 | Train acc: 0.8812 | Test loss: 0.8528 | Test acc: 0.6360 |  F1 score: 0.6133   


 22%|██▎       | 9/40 [01:50<06:14, 12.07s/it]

Epoch: 9 | Train loss: 0.2919 | Train acc: 0.8969 | Test loss: 0.7619 | Test acc: 0.6769 |  F1 score: 0.6744   


 28%|██▊       | 11/40 [02:14<05:42, 11.81s/it]

Epoch: 10 | Train loss: 0.2481 | Train acc: 0.8994 | Test loss: 0.8318 | Test acc: 0.6255 |  F1 score: 0.6109   


 30%|███       | 12/40 [02:25<05:22, 11.52s/it]

Epoch: 11 | Train loss: 0.2359 | Train acc: 0.9119 | Test loss: 1.6538 | Test acc: 0.5124 |  F1 score: 0.4115   
Epoch: 12 | Train loss: 0.2089 | Train acc: 0.9344 | Test loss: 0.7575 | Test acc: 0.6536 |  F1 score: 0.6392   


 32%|███▎      | 13/40 [02:37<05:16, 11.72s/it]

Epoch: 13 | Train loss: 0.1541 | Train acc: 0.9516 | Test loss: 0.7144 | Test acc: 0.6815 |  F1 score: 0.6727   


 38%|███▊      | 15/40 [03:00<04:50, 11.60s/it]

Epoch: 14 | Train loss: 0.1835 | Train acc: 0.9328 | Test loss: 0.7338 | Test acc: 0.7047 |  F1 score: 0.6987   


 40%|████      | 16/40 [03:11<04:33, 11.38s/it]

Epoch: 15 | Train loss: 0.1198 | Train acc: 0.9719 | Test loss: 0.7674 | Test acc: 0.6954 |  F1 score: 0.6817   


 42%|████▎     | 17/40 [03:22<04:18, 11.23s/it]

Epoch: 16 | Train loss: 0.1373 | Train acc: 0.9609 | Test loss: 0.8017 | Test acc: 0.6829 |  F1 score: 0.6634   


 42%|████▎     | 17/40 [03:29<04:44, 12.35s/it]


KeyboardInterrupt: 

output == 7 pretrain VGG

In [ ]:
import torchvision.models as models

model_preTrained_VGG16 = models.vgg16(pretrained=True)    # 使用內建的 model 


optimizer = torch.optim.SGD(model_preTrained_VGG16.parameters(), lr = 0.001) # 選擇你想用的 optimizer

# optimizer = torch.optim.Adam(model_VGG16.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 

#=========
import torch
import torch.nn as nn
import torchvision.models as models




# 获取分类器中最后一个全连接层之前的部分
classifier = list(model_preTrained_VGG16.classifier.children())[:-1]

# 移除原始模型的最后一个全连接层
# 并添加一个新的全连接层，输出特征数为 7
classifier.append(torch.nn.Linear(4096, 7))

# 替换原始模型的分类器
model_preTrained_VGG16.classifier = torch.nn.Sequential(*classifier)

# ============


model_preTrained_VGG16 =  model_preTrained_VGG16.to(device)

from torchinfo import summary

summary(model_preTrained_VGG16, input_size=[1,3,224,224])



# Start the timer


# from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG16_results = train(model=model_preTrained_VGG16,
              train_dataloader=train_dataloader,
              test_dataloader=test_dataloader,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name=model_folder_path + "\\best_model_pretrain_VGG16.pth",
              epochs=40)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")

c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  0%|          | 0/40 [00:00<?, ?it/s]

Epoch: 0 | Train loss: 2.0036 | Train acc: 0.1453 | Test loss: 1.7867 | Test acc: 0.2851 |  F1 score: 0.2716   


  2%|▎         | 1/40 [00:12<07:59, 12.31s/it]

Epoch: 1 | Train loss: 1.6366 | Train acc: 0.3247 | Test loss: 1.5132 | Test acc: 0.4745 |  F1 score: 0.4503   


  5%|▌         | 2/40 [00:24<07:44, 12.23s/it]

Epoch: 2 | Train loss: 1.3936 | Train acc: 0.4131 | Test loss: 1.2942 | Test acc: 0.5067 |  F1 score: 0.4523   


  8%|▊         | 3/40 [00:36<07:27, 12.10s/it]

Epoch: 3 | Train loss: 1.2038 | Train acc: 0.4881 | Test loss: 1.1363 | Test acc: 0.5476 |  F1 score: 0.5151   


 10%|█         | 4/40 [00:48<07:17, 12.15s/it]

Epoch: 4 | Train loss: 1.0641 | Train acc: 0.5425 | Test loss: 1.0493 | Test acc: 0.5681 |  F1 score: 0.5110   


 12%|█▎        | 5/40 [01:00<06:59, 11.99s/it]

Epoch: 5 | Train loss: 1.0007 | Train acc: 0.5606 | Test loss: 1.0072 | Test acc: 0.5632 |  F1 score: 0.5042   


 15%|█▌        | 6/40 [01:12<06:44, 11.89s/it]

Epoch: 6 | Train loss: 0.9325 | Train acc: 0.5847 | Test loss: 0.9422 | Test acc: 0.5792 |  F1 score: 0.5432   


 18%|█▊        | 7/40 [01:24<06:35, 11.98s/it]

Epoch: 7 | Train loss: 0.8177 | Train acc: 0.6478 | Test loss: 0.9106 | Test acc: 0.5809 |  F1 score: 0.5333   


 22%|██▎       | 9/40 [01:46<05:59, 11.59s/it]

Epoch: 8 | Train loss: 0.8065 | Train acc: 0.6572 | Test loss: 0.9247 | Test acc: 0.5598 |  F1 score: 0.4608   
Epoch: 9 | Train loss: 0.8076 | Train acc: 0.6659 | Test loss: 0.8636 | Test acc: 0.6155 |  F1 score: 0.6065   


 25%|██▌       | 10/40 [01:58<05:50, 11.69s/it]

Epoch: 10 | Train loss: 0.7075 | Train acc: 0.6838 | Test loss: 0.8531 | Test acc: 0.5962 |  F1 score: 0.5483   


 30%|███       | 12/40 [02:21<05:21, 11.46s/it]

Epoch: 11 | Train loss: 0.6851 | Train acc: 0.7009 | Test loss: 0.8617 | Test acc: 0.5675 |  F1 score: 0.5362   
Epoch: 12 | Train loss: 0.6216 | Train acc: 0.7431 | Test loss: 0.8333 | Test acc: 0.5769 |  F1 score: 0.5513   


 32%|███▎      | 13/40 [02:33<05:14, 11.66s/it]

Epoch: 13 | Train loss: 0.6021 | Train acc: 0.7488 | Test loss: 0.8042 | Test acc: 0.5885 |  F1 score: 0.5702   


 35%|███▌      | 14/40 [02:45<05:05, 11.76s/it]

Epoch: 14 | Train loss: 0.5770 | Train acc: 0.7784 | Test loss: 0.7778 | Test acc: 0.6130 |  F1 score: 0.5865   


 40%|████      | 16/40 [03:08<04:34, 11.45s/it]

Epoch: 15 | Train loss: 0.5163 | Train acc: 0.7878 | Test loss: 0.8222 | Test acc: 0.6067 |  F1 score: 0.5527   
Epoch: 16 | Train loss: 0.4756 | Train acc: 0.8078 | Test loss: 0.7752 | Test acc: 0.6255 |  F1 score: 0.5948   


 45%|████▌     | 18/40 [03:30<04:09, 11.35s/it]

Epoch: 17 | Train loss: 0.4706 | Train acc: 0.8028 | Test loss: 0.8132 | Test acc: 0.6138 |  F1 score: 0.5899   
Epoch: 18 | Train loss: 0.4279 | Train acc: 0.8391 | Test loss: 0.7151 | Test acc: 0.6612 |  F1 score: 0.6622   


 50%|█████     | 20/40 [03:53<03:45, 11.29s/it]

Epoch: 19 | Train loss: 0.3987 | Train acc: 0.8353 | Test loss: 0.8050 | Test acc: 0.6229 |  F1 score: 0.5982   


 52%|█████▎    | 21/40 [04:04<03:30, 11.10s/it]

Epoch: 20 | Train loss: 0.3727 | Train acc: 0.8469 | Test loss: 0.7364 | Test acc: 0.6692 |  F1 score: 0.6610   
Epoch: 21 | Train loss: 0.3552 | Train acc: 0.8603 | Test loss: 0.6911 | Test acc: 0.6723 |  F1 score: 0.6723   


 57%|█████▊    | 23/40 [04:27<03:10, 11.21s/it]

Epoch: 22 | Train loss: 0.3319 | Train acc: 0.8806 | Test loss: 0.7502 | Test acc: 0.6473 |  F1 score: 0.6327   
Epoch: 23 | Train loss: 0.3006 | Train acc: 0.8922 | Test loss: 0.6809 | Test acc: 0.7005 |  F1 score: 0.7004   


 60%|██████    | 24/40 [04:39<03:03, 11.48s/it]

Epoch: 24 | Train loss: 0.2676 | Train acc: 0.9109 | Test loss: 0.6353 | Test acc: 0.7204 |  F1 score: 0.7204   


 65%|██████▌   | 26/40 [05:02<02:39, 11.37s/it]

Epoch: 25 | Train loss: 0.2001 | Train acc: 0.9213 | Test loss: 0.7778 | Test acc: 0.6553 |  F1 score: 0.6223   


 68%|██████▊   | 27/40 [05:12<02:25, 11.16s/it]

Epoch: 26 | Train loss: 0.2564 | Train acc: 0.9088 | Test loss: 0.7808 | Test acc: 0.6479 |  F1 score: 0.6309   


 70%|███████   | 28/40 [05:23<02:12, 11.02s/it]

Epoch: 27 | Train loss: 0.2474 | Train acc: 0.9128 | Test loss: 0.8346 | Test acc: 0.6257 |  F1 score: 0.5943   
Epoch: 28 | Train loss: 0.2118 | Train acc: 0.9344 | Test loss: 0.6145 | Test acc: 0.7258 |  F1 score: 0.7242   


 75%|███████▌  | 30/40 [05:45<01:50, 11.08s/it]

Epoch: 29 | Train loss: 0.2082 | Train acc: 0.9159 | Test loss: 0.9124 | Test acc: 0.6218 |  F1 score: 0.5946   
Epoch: 30 | Train loss: 0.1788 | Train acc: 0.9359 | Test loss: 0.5847 | Test acc: 0.7383 |  F1 score: 0.7368   


 78%|███████▊  | 31/40 [05:58<01:42, 11.41s/it]

Epoch: 31 | Train loss: 0.1378 | Train acc: 0.9547 | Test loss: 0.5823 | Test acc: 0.7360 |  F1 score: 0.7360   


 82%|████████▎ | 33/40 [06:21<01:20, 11.53s/it]

Epoch: 32 | Train loss: 0.1486 | Train acc: 0.9469 | Test loss: 0.6051 | Test acc: 0.7411 |  F1 score: 0.7409   


 85%|████████▌ | 34/40 [06:32<01:07, 11.28s/it]

Epoch: 33 | Train loss: 0.1328 | Train acc: 0.9594 | Test loss: 0.6604 | Test acc: 0.7272 |  F1 score: 0.7245   


 88%|████████▊ | 35/40 [06:43<00:55, 11.10s/it]

Epoch: 34 | Train loss: 0.1237 | Train acc: 0.9531 | Test loss: 0.5943 | Test acc: 0.7190 |  F1 score: 0.7174   
Epoch: 35 | Train loss: 0.1048 | Train acc: 0.9734 | Test loss: 0.5770 | Test acc: 0.7397 |  F1 score: 0.7391   


 92%|█████████▎| 37/40 [07:05<00:33, 11.16s/it]

Epoch: 36 | Train loss: 0.1102 | Train acc: 0.9641 | Test loss: 0.5821 | Test acc: 0.7622 |  F1 score: 0.7597   
Epoch: 37 | Train loss: 0.0860 | Train acc: 0.9750 | Test loss: 0.5656 | Test acc: 0.7477 |  F1 score: 0.7470   


 95%|█████████▌| 38/40 [07:17<00:22, 11.37s/it]

output == 7 non-pretrain VGG

In [ ]:
import torchvision.models as models

model_VGG16_7 = models.vgg16(pretrained=False)    # 使用內建的 model 


optimizer = torch.optim.SGD(model_VGG16_7.parameters(), lr = 0.001) # 選擇你想用的 optimizer

# optimizer = torch.optim.Adam(model_VGG16.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 

#=========
import torch
import torch.nn as nn
import torchvision.models as models




# 获取分类器中最后一个全连接层之前的部分
classifier = list(model_VGG16_7.classifier.children())[:-1]

# 移除原始模型的最后一个全连接层
# 并添加一个新的全连接层，输出特征数为 7
classifier.append(torch.nn.Linear(4096, 7))

# 替换原始模型的分类器
model_VGG16_7.classifier = torch.nn.Sequential(*classifier)

# ============


model_VGG16_7 =  model_VGG16_7.to(device)



# from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG16_7_results = train(model=model_preTrained_VGG16_7,
              train_dataloader=train_data_loader_224,
              test_dataloader=test_data_loader_224,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name="best_model_VGG16_7.pth",
              epochs=120)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")


c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
  1%|          | 1/120 [01:38<3:15:23, 98.52s/it]

Epoch: 0 | Train loss: 0.3846 | Train acc: 0.8590 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  2%|▏         | 2/120 [03:16<3:13:32, 98.42s/it]

Epoch: 1 | Train loss: 0.3843 | Train acc: 0.8542 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  2%|▎         | 3/120 [04:55<3:12:00, 98.46s/it]

Epoch: 2 | Train loss: 0.3842 | Train acc: 0.8560 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  3%|▎         | 4/120 [06:33<3:10:19, 98.44s/it]

Epoch: 3 | Train loss: 0.3823 | Train acc: 0.8580 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  4%|▍         | 5/120 [08:12<3:08:48, 98.51s/it]

Epoch: 4 | Train loss: 0.3851 | Train acc: 0.8556 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  5%|▌         | 6/120 [09:51<3:07:22, 98.61s/it]

Epoch: 5 | Train loss: 0.3897 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  6%|▌         | 7/120 [11:30<3:05:50, 98.67s/it]

Epoch: 6 | Train loss: 0.3797 | Train acc: 0.8581 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  7%|▋         | 8/120 [13:08<3:04:15, 98.71s/it]

Epoch: 7 | Train loss: 0.3818 | Train acc: 0.8556 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  8%|▊         | 9/120 [14:47<3:02:40, 98.74s/it]

Epoch: 8 | Train loss: 0.3918 | Train acc: 0.8485 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  8%|▊         | 10/120 [16:26<3:01:04, 98.77s/it]

Epoch: 9 | Train loss: 0.3843 | Train acc: 0.8551 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


  9%|▉         | 11/120 [18:05<2:59:40, 98.91s/it]

Epoch: 10 | Train loss: 0.3896 | Train acc: 0.8525 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 10%|█         | 12/120 [19:44<2:58:03, 98.92s/it]

Epoch: 11 | Train loss: 0.3792 | Train acc: 0.8613 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 11%|█         | 13/120 [21:23<2:56:22, 98.90s/it]

Epoch: 12 | Train loss: 0.3900 | Train acc: 0.8503 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 12%|█▏        | 14/120 [23:05<2:56:10, 99.73s/it]

Epoch: 13 | Train loss: 0.3839 | Train acc: 0.8572 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 12%|█▎        | 15/120 [24:50<2:57:36, 101.49s/it]

Epoch: 14 | Train loss: 0.3822 | Train acc: 0.8540 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 13%|█▎        | 16/120 [26:32<2:55:54, 101.49s/it]

Epoch: 15 | Train loss: 0.3875 | Train acc: 0.8549 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 14%|█▍        | 17/120 [28:13<2:53:54, 101.31s/it]

Epoch: 16 | Train loss: 0.3875 | Train acc: 0.8496 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 15%|█▌        | 18/120 [29:53<2:51:59, 101.17s/it]

Epoch: 17 | Train loss: 0.3900 | Train acc: 0.8539 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 16%|█▌        | 19/120 [31:35<2:50:28, 101.27s/it]

Epoch: 18 | Train loss: 0.3920 | Train acc: 0.8517 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 17%|█▋        | 20/120 [33:16<2:48:45, 101.25s/it]

Epoch: 19 | Train loss: 0.3813 | Train acc: 0.8562 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 18%|█▊        | 21/120 [34:58<2:47:11, 101.33s/it]

Epoch: 20 | Train loss: 0.3868 | Train acc: 0.8489 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 18%|█▊        | 22/120 [36:39<2:45:30, 101.33s/it]

Epoch: 21 | Train loss: 0.3915 | Train acc: 0.8539 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 19%|█▉        | 23/120 [38:20<2:43:51, 101.36s/it]

Epoch: 22 | Train loss: 0.3884 | Train acc: 0.8525 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 20%|██        | 24/120 [40:01<2:41:59, 101.25s/it]

Epoch: 23 | Train loss: 0.3853 | Train acc: 0.8539 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 21%|██        | 25/120 [41:42<2:40:13, 101.20s/it]

Epoch: 24 | Train loss: 0.3808 | Train acc: 0.8590 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 22%|██▏       | 26/120 [43:24<2:38:39, 101.27s/it]

Epoch: 25 | Train loss: 0.3836 | Train acc: 0.8555 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 22%|██▎       | 27/120 [45:05<2:36:46, 101.14s/it]

Epoch: 26 | Train loss: 0.3862 | Train acc: 0.8525 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 23%|██▎       | 28/120 [46:46<2:35:04, 101.14s/it]

Epoch: 27 | Train loss: 0.3870 | Train acc: 0.8516 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 24%|██▍       | 29/120 [48:27<2:33:20, 101.10s/it]

Epoch: 28 | Train loss: 0.3906 | Train acc: 0.8505 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 25%|██▌       | 30/120 [50:08<2:31:46, 101.18s/it]

Epoch: 29 | Train loss: 0.3882 | Train acc: 0.8510 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 26%|██▌       | 31/120 [51:49<2:29:59, 101.12s/it]

Epoch: 30 | Train loss: 0.3872 | Train acc: 0.8553 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 27%|██▋       | 32/120 [53:30<2:28:14, 101.08s/it]

Epoch: 31 | Train loss: 0.3878 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 28%|██▊       | 33/120 [55:11<2:26:16, 100.88s/it]

Epoch: 32 | Train loss: 0.3839 | Train acc: 0.8510 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 28%|██▊       | 34/120 [56:49<2:23:42, 100.26s/it]

Epoch: 33 | Train loss: 0.3813 | Train acc: 0.8548 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 29%|██▉       | 35/120 [58:28<2:21:26, 99.84s/it] 

Epoch: 34 | Train loss: 0.3823 | Train acc: 0.8540 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 30%|███       | 36/120 [1:00:07<2:19:25, 99.58s/it]

Epoch: 35 | Train loss: 0.3884 | Train acc: 0.8542 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 31%|███       | 37/120 [1:01:46<2:17:33, 99.43s/it]

Epoch: 36 | Train loss: 0.3856 | Train acc: 0.8592 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 32%|███▏      | 38/120 [1:03:26<2:15:48, 99.37s/it]

Epoch: 37 | Train loss: 0.3867 | Train acc: 0.8556 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 32%|███▎      | 39/120 [1:05:04<2:13:54, 99.20s/it]

Epoch: 38 | Train loss: 0.3872 | Train acc: 0.8574 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 33%|███▎      | 40/120 [1:06:44<2:12:15, 99.19s/it]

Epoch: 39 | Train loss: 0.3891 | Train acc: 0.8560 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 34%|███▍      | 41/120 [1:08:22<2:10:28, 99.10s/it]

Epoch: 40 | Train loss: 0.3861 | Train acc: 0.8565 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 35%|███▌      | 42/120 [1:10:01<2:08:44, 99.03s/it]

Epoch: 41 | Train loss: 0.3829 | Train acc: 0.8587 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 36%|███▌      | 43/120 [1:11:40<2:07:00, 98.97s/it]

Epoch: 42 | Train loss: 0.3885 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 37%|███▋      | 44/120 [1:13:19<2:05:19, 98.94s/it]

Epoch: 43 | Train loss: 0.3867 | Train acc: 0.8525 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 38%|███▊      | 45/120 [1:14:58<2:03:47, 99.04s/it]

Epoch: 44 | Train loss: 0.3875 | Train acc: 0.8551 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 38%|███▊      | 46/120 [1:16:37<2:02:06, 99.01s/it]

Epoch: 45 | Train loss: 0.3895 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 39%|███▉      | 47/120 [1:18:16<2:00:23, 98.95s/it]

Epoch: 46 | Train loss: 0.3932 | Train acc: 0.8539 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 40%|████      | 48/120 [1:19:55<1:58:38, 98.87s/it]

Epoch: 47 | Train loss: 0.3900 | Train acc: 0.8560 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 41%|████      | 49/120 [1:21:34<1:57:00, 98.88s/it]

Epoch: 48 | Train loss: 0.3925 | Train acc: 0.8530 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 42%|████▏     | 50/120 [1:23:12<1:55:15, 98.79s/it]

Epoch: 49 | Train loss: 0.3876 | Train acc: 0.8546 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 42%|████▎     | 51/120 [1:24:51<1:53:37, 98.81s/it]

Epoch: 50 | Train loss: 0.3906 | Train acc: 0.8523 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 43%|████▎     | 52/120 [1:26:30<1:52:00, 98.83s/it]

Epoch: 51 | Train loss: 0.3899 | Train acc: 0.8535 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 44%|████▍     | 53/120 [1:28:09<1:50:22, 98.84s/it]

Epoch: 52 | Train loss: 0.3879 | Train acc: 0.8537 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 45%|████▌     | 54/120 [1:29:47<1:48:40, 98.80s/it]

Epoch: 53 | Train loss: 0.3978 | Train acc: 0.8494 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 46%|████▌     | 55/120 [1:31:26<1:47:01, 98.79s/it]

Epoch: 54 | Train loss: 0.3806 | Train acc: 0.8544 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 47%|████▋     | 56/120 [1:33:05<1:45:16, 98.70s/it]

Epoch: 55 | Train loss: 0.3830 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 48%|████▊     | 57/120 [1:34:43<1:43:37, 98.69s/it]

Epoch: 56 | Train loss: 0.3855 | Train acc: 0.8507 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 48%|████▊     | 58/120 [1:36:22<1:42:02, 98.75s/it]

Epoch: 57 | Train loss: 0.3832 | Train acc: 0.8551 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 49%|████▉     | 59/120 [1:38:01<1:40:30, 98.86s/it]

Epoch: 58 | Train loss: 0.3842 | Train acc: 0.8548 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 50%|█████     | 60/120 [1:39:40<1:38:54, 98.91s/it]

Epoch: 59 | Train loss: 0.3789 | Train acc: 0.8537 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 51%|█████     | 61/120 [1:41:19<1:37:17, 98.94s/it]

Epoch: 60 | Train loss: 0.3978 | Train acc: 0.8475 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 52%|█████▏    | 62/120 [1:42:58<1:35:35, 98.89s/it]

Epoch: 61 | Train loss: 0.3917 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 52%|█████▎    | 63/120 [1:44:37<1:33:57, 98.91s/it]

Epoch: 62 | Train loss: 0.3908 | Train acc: 0.8528 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 53%|█████▎    | 64/120 [1:46:16<1:32:22, 98.97s/it]

Epoch: 63 | Train loss: 0.3883 | Train acc: 0.8530 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 54%|█████▍    | 65/120 [1:47:55<1:30:45, 99.00s/it]

Epoch: 64 | Train loss: 0.3888 | Train acc: 0.8558 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 55%|█████▌    | 66/120 [1:49:34<1:29:06, 99.01s/it]

Epoch: 65 | Train loss: 0.3852 | Train acc: 0.8549 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 56%|█████▌    | 67/120 [1:51:13<1:27:26, 99.00s/it]

Epoch: 66 | Train loss: 0.3842 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 57%|█████▋    | 68/120 [1:52:52<1:25:42, 98.90s/it]

Epoch: 67 | Train loss: 0.3867 | Train acc: 0.8587 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 57%|█████▊    | 69/120 [1:54:31<1:24:00, 98.84s/it]

Epoch: 68 | Train loss: 0.3922 | Train acc: 0.8496 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 58%|█████▊    | 70/120 [1:56:09<1:22:20, 98.80s/it]

Epoch: 69 | Train loss: 0.3857 | Train acc: 0.8549 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 59%|█████▉    | 71/120 [1:57:48<1:20:43, 98.84s/it]

Epoch: 70 | Train loss: 0.3915 | Train acc: 0.8510 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 60%|██████    | 72/120 [1:59:27<1:19:06, 98.88s/it]

Epoch: 71 | Train loss: 0.3850 | Train acc: 0.8574 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 61%|██████    | 73/120 [2:01:06<1:17:28, 98.90s/it]

Epoch: 72 | Train loss: 0.3902 | Train acc: 0.8485 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 62%|██████▏   | 74/120 [2:02:45<1:15:50, 98.93s/it]

Epoch: 73 | Train loss: 0.3811 | Train acc: 0.8585 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 62%|██████▎   | 75/120 [2:04:24<1:14:11, 98.93s/it]

Epoch: 74 | Train loss: 0.3834 | Train acc: 0.8553 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 63%|██████▎   | 76/120 [2:06:03<1:12:29, 98.85s/it]

Epoch: 75 | Train loss: 0.3827 | Train acc: 0.8509 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 64%|██████▍   | 77/120 [2:07:42<1:10:49, 98.83s/it]

Epoch: 76 | Train loss: 0.3880 | Train acc: 0.8539 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 65%|██████▌   | 78/120 [2:09:21<1:09:10, 98.83s/it]

Epoch: 77 | Train loss: 0.3891 | Train acc: 0.8517 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 66%|██████▌   | 79/120 [2:10:59<1:07:33, 98.86s/it]

Epoch: 78 | Train loss: 0.3830 | Train acc: 0.8542 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 67%|██████▋   | 80/120 [2:12:38<1:05:51, 98.80s/it]

Epoch: 79 | Train loss: 0.3900 | Train acc: 0.8517 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 68%|██████▊   | 81/120 [2:14:17<1:04:15, 98.85s/it]

Epoch: 80 | Train loss: 0.3853 | Train acc: 0.8560 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 68%|██████▊   | 82/120 [2:15:56<1:02:36, 98.85s/it]

Epoch: 81 | Train loss: 0.3851 | Train acc: 0.8599 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 69%|██████▉   | 83/120 [2:17:35<1:00:55, 98.78s/it]

Epoch: 82 | Train loss: 0.3897 | Train acc: 0.8539 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 70%|███████   | 84/120 [2:19:13<59:16, 98.78s/it]  

Epoch: 83 | Train loss: 0.3885 | Train acc: 0.8514 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 71%|███████   | 85/120 [2:20:52<57:39, 98.85s/it]

Epoch: 84 | Train loss: 0.3860 | Train acc: 0.8540 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 72%|███████▏  | 86/120 [2:22:31<56:02, 98.90s/it]

Epoch: 85 | Train loss: 0.3894 | Train acc: 0.8503 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 72%|███████▎  | 87/120 [2:24:10<54:25, 98.96s/it]

Epoch: 86 | Train loss: 0.3863 | Train acc: 0.8494 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 73%|███████▎  | 88/120 [2:25:49<52:46, 98.94s/it]

Epoch: 87 | Train loss: 0.3871 | Train acc: 0.8588 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 74%|███████▍  | 89/120 [2:27:28<51:08, 98.97s/it]

Epoch: 88 | Train loss: 0.3843 | Train acc: 0.8587 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 75%|███████▌  | 90/120 [2:29:08<49:33, 99.10s/it]

Epoch: 89 | Train loss: 0.3835 | Train acc: 0.8540 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 76%|███████▌  | 91/120 [2:30:47<47:54, 99.14s/it]

Epoch: 90 | Train loss: 0.3922 | Train acc: 0.8501 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 77%|███████▋  | 92/120 [2:32:26<46:16, 99.18s/it]

Epoch: 91 | Train loss: 0.3966 | Train acc: 0.8530 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 78%|███████▊  | 93/120 [2:34:06<44:40, 99.27s/it]

Epoch: 92 | Train loss: 0.3844 | Train acc: 0.8542 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 78%|███████▊  | 94/120 [2:35:45<43:01, 99.29s/it]

Epoch: 93 | Train loss: 0.3863 | Train acc: 0.8544 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 79%|███████▉  | 95/120 [2:37:24<41:22, 99.31s/it]

Epoch: 94 | Train loss: 0.3849 | Train acc: 0.8505 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 80%|████████  | 96/120 [2:39:04<39:44, 99.36s/it]

Epoch: 95 | Train loss: 0.3866 | Train acc: 0.8546 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 81%|████████  | 97/120 [2:40:43<38:04, 99.31s/it]

Epoch: 96 | Train loss: 0.3864 | Train acc: 0.8535 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 82%|████████▏ | 98/120 [2:42:22<36:21, 99.16s/it]

Epoch: 97 | Train loss: 0.3909 | Train acc: 0.8505 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 82%|████████▎ | 99/120 [2:44:01<34:42, 99.18s/it]

Epoch: 98 | Train loss: 0.3916 | Train acc: 0.8514 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 83%|████████▎ | 100/120 [2:45:40<33:02, 99.14s/it]

Epoch: 99 | Train loss: 0.3868 | Train acc: 0.8572 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 84%|████████▍ | 101/120 [2:47:19<31:22, 99.08s/it]

Epoch: 100 | Train loss: 0.3911 | Train acc: 0.8530 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 85%|████████▌ | 102/120 [2:48:58<29:42, 99.00s/it]

Epoch: 101 | Train loss: 0.3863 | Train acc: 0.8558 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 86%|████████▌ | 103/120 [2:50:37<28:01, 98.90s/it]

Epoch: 102 | Train loss: 0.3899 | Train acc: 0.8523 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 87%|████████▋ | 104/120 [2:52:16<26:22, 98.94s/it]

Epoch: 103 | Train loss: 0.3867 | Train acc: 0.8564 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 88%|████████▊ | 105/120 [2:53:55<24:44, 98.96s/it]

Epoch: 104 | Train loss: 0.3854 | Train acc: 0.8539 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 88%|████████▊ | 106/120 [2:55:34<23:06, 99.04s/it]

Epoch: 105 | Train loss: 0.3865 | Train acc: 0.8519 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 89%|████████▉ | 107/120 [2:57:13<21:27, 99.03s/it]

Epoch: 106 | Train loss: 0.3841 | Train acc: 0.8558 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 90%|█████████ | 108/120 [2:58:52<19:48, 99.04s/it]

Epoch: 107 | Train loss: 0.3876 | Train acc: 0.8537 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 91%|█████████ | 109/120 [3:00:31<18:08, 98.94s/it]

Epoch: 108 | Train loss: 0.3873 | Train acc: 0.8540 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 92%|█████████▏| 110/120 [3:02:09<16:28, 98.83s/it]

Epoch: 109 | Train loss: 0.3890 | Train acc: 0.8532 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 92%|█████████▎| 111/120 [3:03:48<14:49, 98.84s/it]

Epoch: 110 | Train loss: 0.3834 | Train acc: 0.8546 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 93%|█████████▎| 112/120 [3:05:27<13:10, 98.83s/it]

Epoch: 111 | Train loss: 0.3832 | Train acc: 0.8565 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 94%|█████████▍| 113/120 [3:07:03<11:25, 97.96s/it]

Epoch: 112 | Train loss: 0.3867 | Train acc: 0.8548 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 95%|█████████▌| 114/120 [3:08:41<09:48, 98.07s/it]

Epoch: 113 | Train loss: 0.3878 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 96%|█████████▌| 115/120 [3:10:20<08:11, 98.22s/it]

Epoch: 114 | Train loss: 0.3853 | Train acc: 0.8519 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 97%|█████████▋| 116/120 [3:11:59<06:33, 98.40s/it]

Epoch: 115 | Train loss: 0.3872 | Train acc: 0.8548 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 98%|█████████▊| 117/120 [3:13:37<04:55, 98.47s/it]

Epoch: 116 | Train loss: 0.3811 | Train acc: 0.8562 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 98%|█████████▊| 118/120 [3:15:16<03:17, 98.54s/it]

Epoch: 117 | Train loss: 0.3822 | Train acc: 0.8560 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


 99%|█████████▉| 119/120 [3:16:54<01:38, 98.56s/it]

Epoch: 118 | Train loss: 0.3831 | Train acc: 0.8608 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


100%|██████████| 120/120 [3:18:33<00:00, 99.28s/it]

Epoch: 119 | Train loss: 0.3847 | Train acc: 0.8533 | Test loss: 0.6782 | Test acc: 0.7466 |  F1 score: 0.7649   


the best test acc is :0.7466
Total training time: 11914.561 seconds


## Resnet 18

pretrain resnet

In [ ]:
import torchvision.models as models

model_preTrained_Resnet18 = models.resnet18(pretrained=True).to(device)     # 使用內建的 model 

summary(model_preTrained_Resnet18, input_size=[1,3,224,224])

optimizer = torch.optim.SGD(model_preTrained_Resnet18.parameters(), lr = 0.001) # 選擇你想用的 optimizer

# optimizer = torch.optim.Adam(model_Resnet18.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 




# Start the timer
from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG_results = train(model=model_preTrained_Resnet18,
              train_dataloader=train_data_loader_224,
              test_dataloader=test_data_loader_224,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name="best_model_pretrain_Resnet18.pth",
              epochs=40)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")

c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  2%|▎         | 1/40 [01:02<40:23, 62.14s/it]

Epoch: 0 | Train loss: 2.4491 | Train acc: 0.5971 | Test loss: 1.2487 | Test acc: 0.6910 |  F1 score: 0.6630   


  5%|▌         | 2/40 [02:04<39:37, 62.56s/it]

Epoch: 1 | Train loss: 0.8927 | Train acc: 0.7424 | Test loss: 0.8683 | Test acc: 0.7302 |  F1 score: 0.7014   


  8%|▊         | 3/40 [03:08<38:43, 62.79s/it]

Epoch: 2 | Train loss: 0.6925 | Train acc: 0.7786 | Test loss: 0.8158 | Test acc: 0.7382 |  F1 score: 0.7050   


 10%|█         | 4/40 [04:10<37:33, 62.59s/it]

Epoch: 3 | Train loss: 0.5976 | Train acc: 0.8063 | Test loss: 0.7517 | Test acc: 0.7458 |  F1 score: 0.7176   


 12%|█▎        | 5/40 [05:13<36:32, 62.64s/it]

Epoch: 4 | Train loss: 0.5263 | Train acc: 0.8230 | Test loss: 0.7399 | Test acc: 0.7687 |  F1 score: 0.7416   


 15%|█▌        | 6/40 [06:15<35:25, 62.52s/it]

Epoch: 5 | Train loss: 0.4537 | Train acc: 0.8455 | Test loss: 0.6838 | Test acc: 0.7721 |  F1 score: 0.7580   


 18%|█▊        | 7/40 [07:17<34:20, 62.44s/it]

Epoch: 6 | Train loss: 0.4153 | Train acc: 0.8596 | Test loss: 0.6934 | Test acc: 0.7682 |  F1 score: 0.7556   


 20%|██        | 8/40 [08:19<33:14, 62.32s/it]

Epoch: 7 | Train loss: 0.3658 | Train acc: 0.8768 | Test loss: 0.7517 | Test acc: 0.7661 |  F1 score: 0.7350   


 22%|██▎       | 9/40 [09:21<32:11, 62.30s/it]

Epoch: 8 | Train loss: 0.3270 | Train acc: 0.8949 | Test loss: 0.6861 | Test acc: 0.7755 |  F1 score: 0.7678   


 25%|██▌       | 10/40 [10:24<31:15, 62.51s/it]

Epoch: 9 | Train loss: 0.2937 | Train acc: 0.9070 | Test loss: 0.7085 | Test acc: 0.7652 |  F1 score: 0.7588   


 28%|██▊       | 11/40 [11:27<30:13, 62.55s/it]

Epoch: 10 | Train loss: 0.2602 | Train acc: 0.9199 | Test loss: 0.6680 | Test acc: 0.7778 |  F1 score: 0.7692   


 30%|███       | 12/40 [12:30<29:10, 62.53s/it]

Epoch: 11 | Train loss: 0.2487 | Train acc: 0.9276 | Test loss: 0.8235 | Test acc: 0.7669 |  F1 score: 0.7363   


 32%|███▎      | 13/40 [13:32<28:11, 62.64s/it]

Epoch: 12 | Train loss: 0.2074 | Train acc: 0.9419 | Test loss: 0.7420 | Test acc: 0.7693 |  F1 score: 0.7469   


 35%|███▌      | 14/40 [14:35<27:05, 62.53s/it]

Epoch: 13 | Train loss: 0.1857 | Train acc: 0.9515 | Test loss: 0.7507 | Test acc: 0.7760 |  F1 score: 0.7555   


 38%|███▊      | 15/40 [15:38<26:07, 62.72s/it]

Epoch: 14 | Train loss: 0.1672 | Train acc: 0.9569 | Test loss: 0.6981 | Test acc: 0.7801 |  F1 score: 0.7581   


 40%|████      | 16/40 [16:41<25:06, 62.75s/it]

Epoch: 15 | Train loss: 0.1465 | Train acc: 0.9670 | Test loss: 0.7037 | Test acc: 0.7821 |  F1 score: 0.7649   


 42%|████▎     | 17/40 [17:43<23:59, 62.57s/it]

Epoch: 16 | Train loss: 0.1278 | Train acc: 0.9703 | Test loss: 0.6734 | Test acc: 0.7808 |  F1 score: 0.7697   


 45%|████▌     | 18/40 [18:45<22:55, 62.53s/it]

Epoch: 17 | Train loss: 0.1207 | Train acc: 0.9714 | Test loss: 0.6918 | Test acc: 0.7888 |  F1 score: 0.7750   


 48%|████▊     | 19/40 [19:48<21:55, 62.63s/it]

Epoch: 18 | Train loss: 0.1090 | Train acc: 0.9767 | Test loss: 0.7116 | Test acc: 0.7899 |  F1 score: 0.7776   


 50%|█████     | 20/40 [20:51<20:52, 62.64s/it]

Epoch: 19 | Train loss: 0.0914 | Train acc: 0.9860 | Test loss: 0.6689 | Test acc: 0.7885 |  F1 score: 0.7796   


 52%|█████▎    | 21/40 [21:53<19:47, 62.48s/it]

Epoch: 20 | Train loss: 0.0797 | Train acc: 0.9881 | Test loss: 0.6697 | Test acc: 0.7941 |  F1 score: 0.7829   


 55%|█████▌    | 22/40 [22:55<18:41, 62.32s/it]

Epoch: 21 | Train loss: 0.0751 | Train acc: 0.9899 | Test loss: 0.6657 | Test acc: 0.7815 |  F1 score: 0.7750   


 57%|█████▊    | 23/40 [23:57<17:40, 62.39s/it]

Epoch: 22 | Train loss: 0.0697 | Train acc: 0.9911 | Test loss: 0.7040 | Test acc: 0.7849 |  F1 score: 0.7737   


 60%|██████    | 24/40 [25:00<16:39, 62.46s/it]

Epoch: 23 | Train loss: 0.0706 | Train acc: 0.9895 | Test loss: 0.7093 | Test acc: 0.7787 |  F1 score: 0.7690   


 62%|██████▎   | 25/40 [26:03<15:37, 62.47s/it]

Epoch: 24 | Train loss: 0.0665 | Train acc: 0.9902 | Test loss: 0.9462 | Test acc: 0.7739 |  F1 score: 0.7517   


 65%|██████▌   | 26/40 [27:05<14:35, 62.56s/it]

Epoch: 25 | Train loss: 0.0578 | Train acc: 0.9911 | Test loss: 0.6808 | Test acc: 0.7872 |  F1 score: 0.7802   


 68%|██████▊   | 27/40 [28:07<13:31, 62.42s/it]

Epoch: 26 | Train loss: 0.0557 | Train acc: 0.9941 | Test loss: 0.7385 | Test acc: 0.7911 |  F1 score: 0.7798   


 70%|███████   | 28/40 [29:10<12:30, 62.50s/it]

Epoch: 27 | Train loss: 0.0504 | Train acc: 0.9931 | Test loss: 0.7110 | Test acc: 0.7858 |  F1 score: 0.7739   


 72%|███████▎  | 29/40 [30:13<11:28, 62.57s/it]

Epoch: 28 | Train loss: 0.0431 | Train acc: 0.9954 | Test loss: 0.7093 | Test acc: 0.7900 |  F1 score: 0.7830   


 75%|███████▌  | 30/40 [31:17<10:31, 63.11s/it]

Epoch: 29 | Train loss: 0.0409 | Train acc: 0.9961 | Test loss: 0.6945 | Test acc: 0.7936 |  F1 score: 0.7807   


 78%|███████▊  | 31/40 [32:24<09:38, 64.27s/it]

Epoch: 30 | Train loss: 0.0388 | Train acc: 0.9968 | Test loss: 0.6887 | Test acc: 0.7892 |  F1 score: 0.7800   


 80%|████████  | 32/40 [33:30<08:37, 64.72s/it]

Epoch: 31 | Train loss: 0.0408 | Train acc: 0.9959 | Test loss: 0.7498 | Test acc: 0.7868 |  F1 score: 0.7684   


 82%|████████▎ | 33/40 [34:35<07:33, 64.72s/it]

Epoch: 32 | Train loss: 0.0387 | Train acc: 0.9959 | Test loss: 0.6940 | Test acc: 0.7936 |  F1 score: 0.7852   


 85%|████████▌ | 34/40 [35:41<06:31, 65.32s/it]

Epoch: 33 | Train loss: 0.0343 | Train acc: 0.9956 | Test loss: 0.7237 | Test acc: 0.7859 |  F1 score: 0.7737   


 88%|████████▊ | 35/40 [36:47<05:27, 65.40s/it]

Epoch: 34 | Train loss: 0.0302 | Train acc: 0.9979 | Test loss: 0.7121 | Test acc: 0.7934 |  F1 score: 0.7841   


 90%|█████████ | 36/40 [37:52<04:21, 65.35s/it]

Epoch: 35 | Train loss: 0.0272 | Train acc: 0.9989 | Test loss: 0.7806 | Test acc: 0.7893 |  F1 score: 0.7740   


 92%|█████████▎| 37/40 [39:00<03:18, 66.19s/it]

Epoch: 36 | Train loss: 0.0283 | Train acc: 0.9972 | Test loss: 0.7046 | Test acc: 0.7927 |  F1 score: 0.7845   


 95%|█████████▌| 38/40 [40:08<02:13, 66.62s/it]

Epoch: 37 | Train loss: 0.0252 | Train acc: 0.9991 | Test loss: 0.7103 | Test acc: 0.7879 |  F1 score: 0.7794   


 98%|█████████▊| 39/40 [41:14<01:06, 66.34s/it]

Epoch: 38 | Train loss: 0.0230 | Train acc: 0.9986 | Test loss: 0.7232 | Test acc: 0.7899 |  F1 score: 0.7801   


100%|██████████| 40/40 [42:20<00:00, 63.52s/it]

Epoch: 39 | Train loss: 0.0211 | Train acc: 0.9984 | Test loss: 0.7264 | Test acc: 0.7878 |  F1 score: 0.7791   
the best test acc is :0.7815
Total training time: 2540.734 seconds


output == 7 pretrain resnet

In [ ]:
import torchvision.models as models

model_preTrained_Resnet18_7 = models.resnet18(pretrained=True)     # 使用內建的 model 


# optimizer = torch.optim.SGD(model_preTrained_Resnet18_7.parameters(), lr = 0.001) # 選擇你想用的 optimizer
optimizer = torch.optim.SGD(model_preTrained_Resnet18_7.parameters(), lr = 0.001, momentum=0.9) # 選擇你想用的 optimizer

# optimizer = torch.optim.Adam(model_Resnet18_7.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 

# ========================

# change fully connected layer to 7
num_ftrs = model_preTrained_Resnet18_7.fc.in_features
model_preTrained_Resnet18_7.fc = nn.Linear(num_ftrs, 7)

# device setting
model_preTrained_Resnet18_7 = model_preTrained_Resnet18_7.to(device)

# ===========================

# summary(model_preTrained_Resnet18_7)


# Start the timer
from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG_results = train(model=model_preTrained_Resnet18_7,
              train_dataloader=train_data_loader_224,
              test_dataloader=test_data_loader_224,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name="best_model_pretrain_Resnet18_7.pth",
              epochs=40)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")

  0%|          | 0/40 [00:29<?, ?it/s]


KeyboardInterrupt: 

output == 7 non-pretrain resnet

In [ ]:
import torchvision.models as models

model_preTrained_Resnet18 = models.resnet18(pretrained=False).to(device)     # 使用內建的 model 

summary(model_preTrained_Resnet18, input_size=[1,3,224,224])

optimizer = torch.optim.SGD(model_preTrained_Resnet18.parameters(), lr = 0.001) # 選擇你想用的 optimizer

# optimizer = torch.optim.Adam(model_Resnet18.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 




# Start the timer
from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG_results = train(model=model_preTrained_Resnet18,
              train_dataloader=train_data_loader_224,
              test_dataloader=test_data_loader_224,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name="best_model_Resnet18.pth",
              epochs=120)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")

c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
  1%|          | 1/120 [01:02<2:03:41, 62.37s/it]

Epoch: 0 | Train loss: 2.5158 | Train acc: 0.6380 | Test loss: 1.5130 | Test acc: 0.6826 |  F1 score: 0.5538   


  2%|▏         | 2/120 [02:05<2:03:11, 62.64s/it]

Epoch: 1 | Train loss: 1.2750 | Train acc: 0.6729 | Test loss: 1.1878 | Test acc: 0.6876 |  F1 score: 0.5695   


  2%|▎         | 3/120 [03:07<2:02:09, 62.65s/it]

Epoch: 2 | Train loss: 1.0810 | Train acc: 0.6795 | Test loss: 1.0929 | Test acc: 0.6841 |  F1 score: 0.5816   


  3%|▎         | 4/120 [04:10<2:01:12, 62.69s/it]

Epoch: 3 | Train loss: 0.9949 | Train acc: 0.6843 | Test loss: 1.0179 | Test acc: 0.6690 |  F1 score: 0.5868   


  4%|▍         | 5/120 [05:12<1:59:52, 62.54s/it]

Epoch: 4 | Train loss: 0.9341 | Train acc: 0.6870 | Test loss: 1.0225 | Test acc: 0.6924 |  F1 score: 0.6242   


  5%|▌         | 6/120 [06:15<1:58:48, 62.53s/it]

Epoch: 5 | Train loss: 0.9009 | Train acc: 0.6918 | Test loss: 0.9197 | Test acc: 0.7009 |  F1 score: 0.6366   


  6%|▌         | 7/120 [07:17<1:57:32, 62.41s/it]

Epoch: 6 | Train loss: 0.8697 | Train acc: 0.7003 | Test loss: 1.0425 | Test acc: 0.6846 |  F1 score: 0.5961   


  7%|▋         | 8/120 [08:19<1:56:02, 62.16s/it]

Epoch: 7 | Train loss: 0.8369 | Train acc: 0.7088 | Test loss: 0.9349 | Test acc: 0.6668 |  F1 score: 0.6333   


  8%|▊         | 9/120 [09:21<1:55:19, 62.34s/it]

Epoch: 8 | Train loss: 0.8170 | Train acc: 0.7113 | Test loss: 1.1576 | Test acc: 0.6071 |  F1 score: 0.6188   


  8%|▊         | 10/120 [10:24<1:54:36, 62.51s/it]

Epoch: 9 | Train loss: 0.8075 | Train acc: 0.7141 | Test loss: 0.8800 | Test acc: 0.6953 |  F1 score: 0.6063   


  9%|▉         | 11/120 [11:27<1:53:37, 62.55s/it]

Epoch: 10 | Train loss: 0.7840 | Train acc: 0.7223 | Test loss: 0.9287 | Test acc: 0.6841 |  F1 score: 0.5623   


 10%|█         | 12/120 [12:29<1:52:21, 62.43s/it]

Epoch: 11 | Train loss: 0.7788 | Train acc: 0.7211 | Test loss: 1.0125 | Test acc: 0.6056 |  F1 score: 0.6167   


 11%|█         | 13/120 [13:32<1:51:32, 62.55s/it]

Epoch: 12 | Train loss: 0.7618 | Train acc: 0.7251 | Test loss: 1.0375 | Test acc: 0.5840 |  F1 score: 0.6103   


 12%|█▏        | 14/120 [14:34<1:50:07, 62.33s/it]

Epoch: 13 | Train loss: 0.7531 | Train acc: 0.7299 | Test loss: 1.0001 | Test acc: 0.6283 |  F1 score: 0.6282   


 12%|█▎        | 15/120 [15:37<1:49:19, 62.47s/it]

Epoch: 14 | Train loss: 0.7407 | Train acc: 0.7433 | Test loss: 1.0715 | Test acc: 0.6013 |  F1 score: 0.6227   


 13%|█▎        | 16/120 [16:39<1:48:23, 62.53s/it]

Epoch: 15 | Train loss: 0.7310 | Train acc: 0.7365 | Test loss: 0.8693 | Test acc: 0.6919 |  F1 score: 0.6606   


 14%|█▍        | 17/120 [17:42<1:47:20, 62.53s/it]

Epoch: 16 | Train loss: 0.7196 | Train acc: 0.7427 | Test loss: 0.8634 | Test acc: 0.6901 |  F1 score: 0.6540   


 15%|█▌        | 18/120 [18:45<1:46:28, 62.63s/it]

Epoch: 17 | Train loss: 0.7191 | Train acc: 0.7433 | Test loss: 0.8004 | Test acc: 0.7133 |  F1 score: 0.6523   


 16%|█▌        | 19/120 [19:47<1:45:13, 62.51s/it]

Epoch: 18 | Train loss: 0.7113 | Train acc: 0.7408 | Test loss: 0.7715 | Test acc: 0.7331 |  F1 score: 0.6819   


 17%|█▋        | 20/120 [20:50<1:44:16, 62.56s/it]

Epoch: 19 | Train loss: 0.6998 | Train acc: 0.7516 | Test loss: 0.7590 | Test acc: 0.7354 |  F1 score: 0.6851   


 18%|█▊        | 21/120 [21:52<1:42:58, 62.41s/it]

Epoch: 20 | Train loss: 0.6934 | Train acc: 0.7512 | Test loss: 1.1049 | Test acc: 0.6086 |  F1 score: 0.6213   


 18%|█▊        | 22/120 [22:54<1:42:00, 62.46s/it]

Epoch: 21 | Train loss: 0.6829 | Train acc: 0.7555 | Test loss: 0.8349 | Test acc: 0.7160 |  F1 score: 0.6394   


 19%|█▉        | 23/120 [23:56<1:40:51, 62.39s/it]

Epoch: 22 | Train loss: 0.6825 | Train acc: 0.7539 | Test loss: 4.2133 | Test acc: 0.1525 |  F1 score: 0.0896   


 20%|██        | 24/120 [24:58<1:39:24, 62.13s/it]

Epoch: 23 | Train loss: 0.6750 | Train acc: 0.7614 | Test loss: 1.0388 | Test acc: 0.6926 |  F1 score: 0.5875   


 21%|██        | 25/120 [26:00<1:38:20, 62.11s/it]

Epoch: 24 | Train loss: 0.6665 | Train acc: 0.7573 | Test loss: 0.9140 | Test acc: 0.7054 |  F1 score: 0.6149   


 22%|██▏       | 26/120 [27:02<1:37:27, 62.21s/it]

Epoch: 25 | Train loss: 0.6627 | Train acc: 0.7640 | Test loss: 3.5391 | Test acc: 0.1844 |  F1 score: 0.1436   


 22%|██▎       | 27/120 [28:05<1:36:48, 62.46s/it]

Epoch: 26 | Train loss: 0.6561 | Train acc: 0.7642 | Test loss: 1.0530 | Test acc: 0.6562 |  F1 score: 0.6710   


 23%|██▎       | 28/120 [29:08<1:35:56, 62.57s/it]

Epoch: 27 | Train loss: 0.6511 | Train acc: 0.7653 | Test loss: 2.6946 | Test acc: 0.2187 |  F1 score: 0.1977   


 24%|██▍       | 29/120 [30:11<1:34:56, 62.60s/it]

Epoch: 28 | Train loss: 0.6500 | Train acc: 0.7681 | Test loss: 1.1295 | Test acc: 0.5957 |  F1 score: 0.6328   


 25%|██▌       | 30/120 [31:14<1:34:01, 62.68s/it]

Epoch: 29 | Train loss: 0.6386 | Train acc: 0.7765 | Test loss: 0.8604 | Test acc: 0.7039 |  F1 score: 0.6367   


 26%|██▌       | 31/120 [32:17<1:33:07, 62.78s/it]

Epoch: 30 | Train loss: 0.6318 | Train acc: 0.7749 | Test loss: 0.8213 | Test acc: 0.7226 |  F1 score: 0.6474   


 27%|██▋       | 32/120 [33:20<1:32:09, 62.84s/it]

Epoch: 31 | Train loss: 0.6328 | Train acc: 0.7740 | Test loss: 0.8111 | Test acc: 0.7162 |  F1 score: 0.6538   


 28%|██▊       | 33/120 [34:22<1:30:54, 62.69s/it]

Epoch: 32 | Train loss: 0.6189 | Train acc: 0.7782 | Test loss: 0.9141 | Test acc: 0.7105 |  F1 score: 0.6208   


 28%|██▊       | 34/120 [35:24<1:29:36, 62.51s/it]

Epoch: 33 | Train loss: 0.6149 | Train acc: 0.7827 | Test loss: 0.7768 | Test acc: 0.7286 |  F1 score: 0.6867   


 29%|██▉       | 35/120 [36:27<1:28:34, 62.52s/it]

Epoch: 34 | Train loss: 0.6051 | Train acc: 0.7811 | Test loss: 1.0617 | Test acc: 0.6174 |  F1 score: 0.6422   


 30%|███       | 36/120 [37:29<1:27:24, 62.44s/it]

Epoch: 35 | Train loss: 0.5991 | Train acc: 0.7825 | Test loss: 2.8117 | Test acc: 0.2180 |  F1 score: 0.1947   


 31%|███       | 37/120 [38:32<1:26:28, 62.51s/it]

Epoch: 36 | Train loss: 0.6015 | Train acc: 0.7843 | Test loss: 1.8059 | Test acc: 0.4367 |  F1 score: 0.4994   


 32%|███▏      | 38/120 [39:34<1:25:26, 62.52s/it]

Epoch: 37 | Train loss: 0.5937 | Train acc: 0.7887 | Test loss: 0.8371 | Test acc: 0.7066 |  F1 score: 0.6662   


 32%|███▎      | 39/120 [40:37<1:24:32, 62.62s/it]

Epoch: 38 | Train loss: 0.5861 | Train acc: 0.7884 | Test loss: 0.9469 | Test acc: 0.7029 |  F1 score: 0.6209   


 33%|███▎      | 40/120 [41:39<1:23:24, 62.55s/it]

Epoch: 39 | Train loss: 0.5796 | Train acc: 0.7903 | Test loss: 1.4841 | Test acc: 0.6841 |  F1 score: 0.5636   


 34%|███▍      | 41/120 [42:42<1:22:17, 62.50s/it]

Epoch: 40 | Train loss: 0.5676 | Train acc: 0.7940 | Test loss: 0.8748 | Test acc: 0.7112 |  F1 score: 0.6263   


 35%|███▌      | 42/120 [43:44<1:21:10, 62.44s/it]

Epoch: 41 | Train loss: 0.5684 | Train acc: 0.7965 | Test loss: 0.8716 | Test acc: 0.6949 |  F1 score: 0.6953   


 36%|███▌      | 43/120 [44:47<1:20:18, 62.57s/it]

Epoch: 42 | Train loss: 0.5556 | Train acc: 0.8031 | Test loss: 1.0110 | Test acc: 0.7073 |  F1 score: 0.6294   


 37%|███▋      | 44/120 [45:50<1:19:17, 62.60s/it]

Epoch: 43 | Train loss: 0.5448 | Train acc: 0.8056 | Test loss: 0.8553 | Test acc: 0.7103 |  F1 score: 0.6688   


 38%|███▊      | 45/120 [46:52<1:18:13, 62.58s/it]

Epoch: 44 | Train loss: 0.5388 | Train acc: 0.8104 | Test loss: 7.6646 | Test acc: 0.1212 |  F1 score: 0.0320   


 38%|███▊      | 46/120 [47:55<1:17:19, 62.70s/it]

Epoch: 45 | Train loss: 0.5331 | Train acc: 0.8084 | Test loss: 0.9830 | Test acc: 0.6660 |  F1 score: 0.6588   


 39%|███▉      | 47/120 [48:58<1:16:20, 62.75s/it]

Epoch: 46 | Train loss: 0.5248 | Train acc: 0.8150 | Test loss: 0.8196 | Test acc: 0.7137 |  F1 score: 0.6776   


 40%|████      | 48/120 [50:01<1:15:21, 62.80s/it]

Epoch: 47 | Train loss: 0.5179 | Train acc: 0.8178 | Test loss: 1.3432 | Test acc: 0.6841 |  F1 score: 0.5601   


 41%|████      | 49/120 [51:04<1:14:17, 62.78s/it]

Epoch: 48 | Train loss: 0.5095 | Train acc: 0.8191 | Test loss: 1.6351 | Test acc: 0.6883 |  F1 score: 0.5698   


 42%|████▏     | 50/120 [52:06<1:13:09, 62.71s/it]

Epoch: 49 | Train loss: 0.5082 | Train acc: 0.8246 | Test loss: 1.3365 | Test acc: 0.5668 |  F1 score: 0.6136   


 42%|████▎     | 51/120 [53:08<1:11:56, 62.56s/it]

Epoch: 50 | Train loss: 0.4962 | Train acc: 0.8232 | Test loss: 0.8341 | Test acc: 0.7290 |  F1 score: 0.6833   


 43%|████▎     | 52/120 [54:11<1:10:52, 62.54s/it]

Epoch: 51 | Train loss: 0.4867 | Train acc: 0.8311 | Test loss: 0.8421 | Test acc: 0.7421 |  F1 score: 0.6763   


 44%|████▍     | 53/120 [55:14<1:09:53, 62.59s/it]

Epoch: 52 | Train loss: 0.4839 | Train acc: 0.8335 | Test loss: 0.9195 | Test acc: 0.6702 |  F1 score: 0.6962   


 45%|████▌     | 54/120 [56:16<1:08:53, 62.63s/it]

Epoch: 53 | Train loss: 0.4687 | Train acc: 0.8395 | Test loss: 0.7968 | Test acc: 0.7041 |  F1 score: 0.6938   


 46%|████▌     | 55/120 [57:19<1:07:41, 62.48s/it]

Epoch: 54 | Train loss: 0.4594 | Train acc: 0.8418 | Test loss: 4.8287 | Test acc: 0.2197 |  F1 score: 0.2138   


 47%|████▋     | 56/120 [58:21<1:06:36, 62.44s/it]

Epoch: 55 | Train loss: 0.4470 | Train acc: 0.8516 | Test loss: 1.9094 | Test acc: 0.4569 |  F1 score: 0.5149   


 48%|████▊     | 57/120 [59:23<1:05:36, 62.48s/it]

Epoch: 56 | Train loss: 0.4380 | Train acc: 0.8494 | Test loss: 1.5683 | Test acc: 0.5273 |  F1 score: 0.5767   


 48%|████▊     | 58/120 [1:00:26<1:04:33, 62.47s/it]

Epoch: 57 | Train loss: 0.4461 | Train acc: 0.8478 | Test loss: 0.8600 | Test acc: 0.7155 |  F1 score: 0.6969   


 49%|████▉     | 59/120 [1:01:28<1:03:22, 62.33s/it]

Epoch: 58 | Train loss: 0.4156 | Train acc: 0.8601 | Test loss: 0.8247 | Test acc: 0.7162 |  F1 score: 0.6952   


 50%|█████     | 60/120 [1:02:30<1:02:08, 62.15s/it]

Epoch: 59 | Train loss: 0.4134 | Train acc: 0.8556 | Test loss: 6.3909 | Test acc: 0.1560 |  F1 score: 0.0959   


 51%|█████     | 61/120 [1:03:32<1:01:12, 62.24s/it]

Epoch: 60 | Train loss: 0.4134 | Train acc: 0.8587 | Test loss: 1.2295 | Test acc: 0.5909 |  F1 score: 0.6243   


 52%|█████▏    | 62/120 [1:04:35<1:00:14, 62.32s/it]

Epoch: 61 | Train loss: 0.3948 | Train acc: 0.8704 | Test loss: 0.8984 | Test acc: 0.6741 |  F1 score: 0.6776   


 52%|█████▎    | 63/120 [1:05:37<59:12, 62.33s/it]  

Epoch: 62 | Train loss: 0.3861 | Train acc: 0.8713 | Test loss: 0.8296 | Test acc: 0.7107 |  F1 score: 0.6985   


 53%|█████▎    | 64/120 [1:06:39<57:59, 62.14s/it]

Epoch: 63 | Train loss: 0.3741 | Train acc: 0.8761 | Test loss: 0.8377 | Test acc: 0.7331 |  F1 score: 0.6932   


 54%|█████▍    | 65/120 [1:07:41<56:58, 62.15s/it]

Epoch: 64 | Train loss: 0.3620 | Train acc: 0.8826 | Test loss: 1.1625 | Test acc: 0.6856 |  F1 score: 0.6318   


 55%|█████▌    | 66/120 [1:08:43<56:00, 62.23s/it]

Epoch: 65 | Train loss: 0.3544 | Train acc: 0.8800 | Test loss: 2.3263 | Test acc: 0.3046 |  F1 score: 0.3297   


 56%|█████▌    | 67/120 [1:09:45<54:56, 62.20s/it]

Epoch: 66 | Train loss: 0.3410 | Train acc: 0.8867 | Test loss: 1.0973 | Test acc: 0.6434 |  F1 score: 0.6559   


 57%|█████▋    | 68/120 [1:10:48<54:07, 62.46s/it]

Epoch: 67 | Train loss: 0.3467 | Train acc: 0.8867 | Test loss: 1.6925 | Test acc: 0.5440 |  F1 score: 0.5958   


 57%|█████▊    | 69/120 [1:11:51<53:10, 62.57s/it]

Epoch: 68 | Train loss: 0.3214 | Train acc: 0.8961 | Test loss: 2.4879 | Test acc: 0.4612 |  F1 score: 0.5052   


 58%|█████▊    | 70/120 [1:12:53<52:00, 62.41s/it]

Epoch: 69 | Train loss: 0.3239 | Train acc: 0.8938 | Test loss: 0.8647 | Test acc: 0.7098 |  F1 score: 0.7089   


 59%|█████▉    | 71/120 [1:13:56<50:58, 62.43s/it]

Epoch: 70 | Train loss: 0.3044 | Train acc: 0.9034 | Test loss: 0.9636 | Test acc: 0.7233 |  F1 score: 0.6777   


 60%|██████    | 72/120 [1:14:58<49:54, 62.38s/it]

Epoch: 71 | Train loss: 0.2948 | Train acc: 0.9071 | Test loss: 1.1336 | Test acc: 0.6924 |  F1 score: 0.6511   


 61%|██████    | 73/120 [1:16:01<49:00, 62.57s/it]

Epoch: 72 | Train loss: 0.2974 | Train acc: 0.9073 | Test loss: 1.3050 | Test acc: 0.7052 |  F1 score: 0.6486   


 62%|██████▏   | 74/120 [1:17:03<47:51, 62.43s/it]

Epoch: 73 | Train loss: 0.2883 | Train acc: 0.9050 | Test loss: 0.7795 | Test acc: 0.7439 |  F1 score: 0.7306   


 62%|██████▎   | 75/120 [1:18:06<46:53, 62.52s/it]

Epoch: 74 | Train loss: 0.2777 | Train acc: 0.9103 | Test loss: 1.0993 | Test acc: 0.6570 |  F1 score: 0.6732   


 63%|██████▎   | 76/120 [1:19:09<45:57, 62.67s/it]

Epoch: 75 | Train loss: 0.2748 | Train acc: 0.9150 | Test loss: 1.0190 | Test acc: 0.6770 |  F1 score: 0.6867   


 64%|██████▍   | 77/120 [1:20:11<44:50, 62.58s/it]

Epoch: 76 | Train loss: 0.2547 | Train acc: 0.9242 | Test loss: 0.9943 | Test acc: 0.6993 |  F1 score: 0.6799   


 65%|██████▌   | 78/120 [1:21:13<43:36, 62.31s/it]

Epoch: 77 | Train loss: 0.2544 | Train acc: 0.9194 | Test loss: 0.8463 | Test acc: 0.7325 |  F1 score: 0.7180   


 66%|██████▌   | 79/120 [1:22:14<42:25, 62.08s/it]

Epoch: 78 | Train loss: 0.2402 | Train acc: 0.9263 | Test loss: 1.6007 | Test acc: 0.6849 |  F1 score: 0.6021   


 67%|██████▋   | 80/120 [1:23:17<41:31, 62.28s/it]

Epoch: 79 | Train loss: 0.2392 | Train acc: 0.9244 | Test loss: 1.1573 | Test acc: 0.6214 |  F1 score: 0.6495   


 68%|██████▊   | 81/120 [1:24:19<40:24, 62.16s/it]

Epoch: 80 | Train loss: 0.2339 | Train acc: 0.9290 | Test loss: 1.8856 | Test acc: 0.5468 |  F1 score: 0.5888   


 68%|██████▊   | 82/120 [1:25:21<39:19, 62.10s/it]

Epoch: 81 | Train loss: 0.2333 | Train acc: 0.9302 | Test loss: 1.6493 | Test acc: 0.5980 |  F1 score: 0.6053   


 69%|██████▉   | 83/120 [1:26:23<38:17, 62.10s/it]

Epoch: 82 | Train loss: 0.2310 | Train acc: 0.9313 | Test loss: 24.1105 | Test acc: 0.1212 |  F1 score: 0.0375   


 70%|███████   | 84/120 [1:27:26<37:20, 62.23s/it]

Epoch: 83 | Train loss: 0.2162 | Train acc: 0.9370 | Test loss: 1.1497 | Test acc: 0.7307 |  F1 score: 0.6695   


 71%|███████   | 85/120 [1:28:28<36:18, 62.25s/it]

Epoch: 84 | Train loss: 0.2024 | Train acc: 0.9409 | Test loss: 1.0558 | Test acc: 0.6777 |  F1 score: 0.6711   


 72%|███████▏  | 86/120 [1:29:30<35:14, 62.20s/it]

Epoch: 85 | Train loss: 0.2029 | Train acc: 0.9384 | Test loss: 2.8351 | Test acc: 0.3896 |  F1 score: 0.4367   


 72%|███████▎  | 87/120 [1:30:32<34:13, 62.22s/it]

Epoch: 86 | Train loss: 0.2022 | Train acc: 0.9402 | Test loss: 0.9838 | Test acc: 0.7098 |  F1 score: 0.6892   


 73%|███████▎  | 88/120 [1:31:35<33:12, 62.27s/it]

Epoch: 87 | Train loss: 0.1783 | Train acc: 0.9482 | Test loss: 0.9014 | Test acc: 0.7373 |  F1 score: 0.7290   


 74%|███████▍  | 89/120 [1:32:37<32:08, 62.22s/it]

Epoch: 88 | Train loss: 0.1756 | Train acc: 0.9515 | Test loss: 1.2495 | Test acc: 0.6788 |  F1 score: 0.6908   


 75%|███████▌  | 90/120 [1:33:39<31:05, 62.17s/it]

Epoch: 89 | Train loss: 0.1764 | Train acc: 0.9485 | Test loss: 6.4468 | Test acc: 0.1743 |  F1 score: 0.1359   


 76%|███████▌  | 91/120 [1:34:41<30:03, 62.18s/it]

Epoch: 90 | Train loss: 0.1638 | Train acc: 0.9508 | Test loss: 10.7207 | Test acc: 0.1704 |  F1 score: 0.1263   


 77%|███████▋  | 92/120 [1:35:44<29:06, 62.37s/it]

Epoch: 91 | Train loss: 0.1687 | Train acc: 0.9524 | Test loss: 1.6198 | Test acc: 0.6959 |  F1 score: 0.6140   


 78%|███████▊  | 93/120 [1:36:47<28:07, 62.50s/it]

Epoch: 92 | Train loss: 0.1597 | Train acc: 0.9565 | Test loss: 1.4525 | Test acc: 0.6252 |  F1 score: 0.6374   


 78%|███████▊  | 94/120 [1:37:50<27:07, 62.60s/it]

Epoch: 93 | Train loss: 0.1483 | Train acc: 0.9581 | Test loss: 1.0423 | Test acc: 0.7339 |  F1 score: 0.7025   


 79%|███████▉  | 95/120 [1:38:52<26:05, 62.62s/it]

Epoch: 94 | Train loss: 0.1449 | Train acc: 0.9640 | Test loss: 2.6182 | Test acc: 0.6855 |  F1 score: 0.5764   


 80%|████████  | 96/120 [1:39:55<25:01, 62.57s/it]

Epoch: 95 | Train loss: 0.1568 | Train acc: 0.9528 | Test loss: 2.0618 | Test acc: 0.5911 |  F1 score: 0.5989   


 81%|████████  | 97/120 [1:40:58<24:02, 62.71s/it]

Epoch: 96 | Train loss: 0.1416 | Train acc: 0.9624 | Test loss: 1.2892 | Test acc: 0.7059 |  F1 score: 0.6517   


 82%|████████▏ | 98/120 [1:42:00<22:57, 62.63s/it]

Epoch: 97 | Train loss: 0.1366 | Train acc: 0.9606 | Test loss: 1.1647 | Test acc: 0.6800 |  F1 score: 0.7002   


 82%|████████▎ | 99/120 [1:43:02<21:49, 62.37s/it]

Epoch: 98 | Train loss: 0.1315 | Train acc: 0.9664 | Test loss: 3.2353 | Test acc: 0.4679 |  F1 score: 0.5262   


 83%|████████▎ | 100/120 [1:44:04<20:48, 62.42s/it]

Epoch: 99 | Train loss: 0.1350 | Train acc: 0.9659 | Test loss: 2.6900 | Test acc: 0.5270 |  F1 score: 0.5367   


 84%|████████▍ | 101/120 [1:45:07<19:45, 62.41s/it]

Epoch: 100 | Train loss: 0.1395 | Train acc: 0.9615 | Test loss: 2.7757 | Test acc: 0.6899 |  F1 score: 0.6096   


 85%|████████▌ | 102/120 [1:46:09<18:39, 62.21s/it]

Epoch: 101 | Train loss: 0.1311 | Train acc: 0.9650 | Test loss: 1.5254 | Test acc: 0.7105 |  F1 score: 0.6450   


 86%|████████▌ | 103/120 [1:47:12<17:41, 62.46s/it]

Epoch: 102 | Train loss: 0.1202 | Train acc: 0.9689 | Test loss: 1.0720 | Test acc: 0.7439 |  F1 score: 0.7132   


 87%|████████▋ | 104/120 [1:48:14<16:37, 62.35s/it]

Epoch: 103 | Train loss: 0.1049 | Train acc: 0.9719 | Test loss: 3.1665 | Test acc: 0.4008 |  F1 score: 0.4591   


 88%|████████▊ | 105/120 [1:49:17<15:39, 62.61s/it]

Epoch: 104 | Train loss: 0.1079 | Train acc: 0.9723 | Test loss: 0.9521 | Test acc: 0.7548 |  F1 score: 0.7371   


 88%|████████▊ | 106/120 [1:50:20<14:38, 62.72s/it]

Epoch: 105 | Train loss: 0.0946 | Train acc: 0.9748 | Test loss: 1.9365 | Test acc: 0.5545 |  F1 score: 0.6022   


 89%|████████▉ | 107/120 [1:51:22<13:32, 62.54s/it]

Epoch: 106 | Train loss: 0.0999 | Train acc: 0.9759 | Test loss: 1.5404 | Test acc: 0.6326 |  F1 score: 0.6621   


 90%|█████████ | 108/120 [1:52:25<12:30, 62.56s/it]

Epoch: 107 | Train loss: 0.0947 | Train acc: 0.9766 | Test loss: 1.6504 | Test acc: 0.6168 |  F1 score: 0.6451   


 91%|█████████ | 109/120 [1:53:26<11:25, 62.34s/it]

Epoch: 108 | Train loss: 0.0999 | Train acc: 0.9737 | Test loss: 2.4960 | Test acc: 0.6954 |  F1 score: 0.6003   


 92%|█████████▏| 110/120 [1:54:29<10:24, 62.50s/it]

Epoch: 109 | Train loss: 0.0994 | Train acc: 0.9759 | Test loss: 2.7912 | Test acc: 0.5398 |  F1 score: 0.5741   


 92%|█████████▎| 111/120 [1:55:32<09:23, 62.59s/it]

Epoch: 110 | Train loss: 0.1006 | Train acc: 0.9780 | Test loss: 1.0480 | Test acc: 0.7272 |  F1 score: 0.7217   


 93%|█████████▎| 112/120 [1:56:35<08:20, 62.57s/it]

Epoch: 111 | Train loss: 0.0877 | Train acc: 0.9771 | Test loss: 3.0189 | Test acc: 0.5382 |  F1 score: 0.5841   


 94%|█████████▍| 113/120 [1:57:38<07:18, 62.70s/it]

Epoch: 112 | Train loss: 0.0883 | Train acc: 0.9789 | Test loss: 1.3077 | Test acc: 0.7284 |  F1 score: 0.6778   


 95%|█████████▌| 114/120 [1:58:40<06:15, 62.64s/it]

Epoch: 113 | Train loss: 0.0947 | Train acc: 0.9746 | Test loss: 1.3949 | Test acc: 0.6940 |  F1 score: 0.6828   


 96%|█████████▌| 115/120 [1:59:43<05:13, 62.77s/it]

Epoch: 114 | Train loss: 0.0865 | Train acc: 0.9759 | Test loss: 4.2331 | Test acc: 0.6613 |  F1 score: 0.5556   


 97%|█████████▋| 116/120 [2:00:46<04:10, 62.74s/it]

Epoch: 115 | Train loss: 0.0958 | Train acc: 0.9728 | Test loss: 3.9656 | Test acc: 0.5046 |  F1 score: 0.5484   


 98%|█████████▊| 117/120 [2:01:48<03:07, 62.58s/it]

Epoch: 116 | Train loss: 0.0770 | Train acc: 0.9830 | Test loss: 1.1152 | Test acc: 0.7379 |  F1 score: 0.7275   


 98%|█████████▊| 118/120 [2:02:51<02:05, 62.59s/it]

Epoch: 117 | Train loss: 0.0678 | Train acc: 0.9853 | Test loss: 1.1070 | Test acc: 0.7281 |  F1 score: 0.7185   


 99%|█████████▉| 119/120 [2:03:53<01:02, 62.51s/it]

Epoch: 118 | Train loss: 0.0760 | Train acc: 0.9819 | Test loss: 1.1065 | Test acc: 0.7446 |  F1 score: 0.7119   


100%|██████████| 120/120 [2:04:55<00:00, 62.46s/it]

Epoch: 119 | Train loss: 0.0631 | Train acc: 0.9860 | Test loss: 1.5772 | Test acc: 0.7105 |  F1 score: 0.6729   
the best test acc is :0.7354
Total training time: 7495.337 seconds


output == 7 pretrain resnet

In [ ]:
import torchvision.models as models

model_preTrained_Resnet18_7 = models.resnet18(pretrained=True)     # 使用內建的 model 


# optimizer = torch.optim.SGD(model_preTrained_Resnet18_7.parameters(), lr = 0.001) # 選擇你想用的 optimizer
optimizer = torch.optim.SGD(model_preTrained_Resnet18_7.parameters(), lr = 0.001, momentum=0.9) # 選擇你想用的 optimizer

# optimizer = torch.optim.Adam(model_Resnet18_7.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 

# ========================

# change fully connected layer to 7
num_ftrs = model_preTrained_Resnet18_7.fc.in_features
model_preTrained_Resnet18_7.fc = nn.Linear(num_ftrs, 7)

# device setting
model_preTrained_Resnet18_7 = model_preTrained_Resnet18_7.to(device)

# ===========================

summary(model_preTrained_Resnet18_7)


# Start the timer
from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG_results = train(model=model_preTrained_Resnet18_7,
              train_dataloader=train_data_loader_224,
              test_dataloader=test_data_loader_224,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name="best_model_Resnet18_7.pth",
              epochs=120)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")

c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  1%|          | 1/120 [01:02<2:03:53, 62.47s/it]

Epoch: 0 | Train loss: 1.4069 | Train acc: 0.5632 | Test loss: 0.9721 | Test acc: 0.7389 |  F1 score: 0.7194   


  2%|▏         | 2/120 [02:04<2:02:39, 62.37s/it]

Epoch: 1 | Train loss: 0.7745 | Train acc: 0.7795 | Test loss: 0.7548 | Test acc: 0.7657 |  F1 score: 0.7325   


  2%|▎         | 3/120 [03:07<2:02:14, 62.68s/it]

Epoch: 2 | Train loss: 0.6390 | Train acc: 0.8155 | Test loss: 0.7108 | Test acc: 0.7865 |  F1 score: 0.7765   


  3%|▎         | 4/120 [04:10<2:01:12, 62.70s/it]

Epoch: 3 | Train loss: 0.4891 | Train acc: 0.8469 | Test loss: 0.7692 | Test acc: 0.7872 |  F1 score: 0.7762   


  4%|▍         | 5/120 [05:13<2:00:10, 62.70s/it]

Epoch: 4 | Train loss: 0.3934 | Train acc: 0.8837 | Test loss: 0.6176 | Test acc: 0.7934 |  F1 score: 0.7682   


  5%|▌         | 6/120 [06:16<1:59:11, 62.73s/it]

Epoch: 5 | Train loss: 0.3107 | Train acc: 0.9142 | Test loss: 0.6684 | Test acc: 0.8047 |  F1 score: 0.7987   


  6%|▌         | 7/120 [07:18<1:57:50, 62.57s/it]

Epoch: 6 | Train loss: 0.2966 | Train acc: 0.9183 | Test loss: 0.5861 | Test acc: 0.8179 |  F1 score: 0.8008   


  7%|▋         | 8/120 [08:21<1:56:58, 62.67s/it]

Epoch: 7 | Train loss: 0.2145 | Train acc: 0.9482 | Test loss: 0.6793 | Test acc: 0.8133 |  F1 score: 0.8043   


  8%|▊         | 9/120 [09:23<1:55:41, 62.54s/it]

Epoch: 8 | Train loss: 0.1473 | Train acc: 0.9702 | Test loss: 0.5975 | Test acc: 0.8328 |  F1 score: 0.8301   


  8%|▊         | 10/120 [10:25<1:54:24, 62.40s/it]

Epoch: 9 | Train loss: 0.1134 | Train acc: 0.9835 | Test loss: 0.6886 | Test acc: 0.8220 |  F1 score: 0.8233   


  9%|▉         | 11/120 [11:28<1:53:35, 62.52s/it]

Epoch: 10 | Train loss: 0.1065 | Train acc: 0.9815 | Test loss: 0.6021 | Test acc: 0.8298 |  F1 score: 0.8168   


 10%|█         | 12/120 [12:30<1:52:14, 62.36s/it]

Epoch: 11 | Train loss: 0.0713 | Train acc: 0.9908 | Test loss: 0.6019 | Test acc: 0.8232 |  F1 score: 0.8168   


 11%|█         | 13/120 [13:33<1:51:34, 62.57s/it]

Epoch: 12 | Train loss: 0.0686 | Train acc: 0.9899 | Test loss: 0.6198 | Test acc: 0.8211 |  F1 score: 0.8082   


 12%|█▏        | 14/120 [14:36<1:50:50, 62.74s/it]

Epoch: 13 | Train loss: 0.0533 | Train acc: 0.9950 | Test loss: 0.6096 | Test acc: 0.8354 |  F1 score: 0.8320   


 12%|█▎        | 15/120 [15:39<1:49:50, 62.77s/it]

Epoch: 14 | Train loss: 0.0593 | Train acc: 0.9904 | Test loss: 0.6259 | Test acc: 0.8191 |  F1 score: 0.8077   


 13%|█▎        | 16/120 [16:42<1:48:47, 62.76s/it]

Epoch: 15 | Train loss: 0.0563 | Train acc: 0.9908 | Test loss: 0.6265 | Test acc: 0.8326 |  F1 score: 0.8261   


 14%|█▍        | 17/120 [17:44<1:47:31, 62.64s/it]

Epoch: 16 | Train loss: 0.0380 | Train acc: 0.9977 | Test loss: 0.6556 | Test acc: 0.8337 |  F1 score: 0.8307   


 15%|█▌        | 18/120 [18:47<1:46:44, 62.79s/it]

Epoch: 17 | Train loss: 0.0297 | Train acc: 0.9988 | Test loss: 0.6436 | Test acc: 0.8291 |  F1 score: 0.8207   


 16%|█▌        | 19/120 [19:50<1:45:40, 62.78s/it]

Epoch: 18 | Train loss: 0.0246 | Train acc: 0.9982 | Test loss: 0.6060 | Test acc: 0.8328 |  F1 score: 0.8255   


 17%|█▋        | 20/120 [20:52<1:44:28, 62.68s/it]

Epoch: 19 | Train loss: 0.0218 | Train acc: 0.9991 | Test loss: 0.6250 | Test acc: 0.8376 |  F1 score: 0.8307   


 18%|█▊        | 21/120 [21:54<1:43:03, 62.46s/it]

Epoch: 20 | Train loss: 0.0217 | Train acc: 0.9995 | Test loss: 0.6180 | Test acc: 0.8413 |  F1 score: 0.8336   


 18%|█▊        | 22/120 [22:57<1:42:17, 62.62s/it]

Epoch: 21 | Train loss: 0.0234 | Train acc: 0.9982 | Test loss: 0.6557 | Test acc: 0.8220 |  F1 score: 0.8057   


 19%|█▉        | 23/120 [24:00<1:41:22, 62.70s/it]

Epoch: 22 | Train loss: 0.0187 | Train acc: 0.9993 | Test loss: 0.6466 | Test acc: 0.8399 |  F1 score: 0.8333   


 20%|██        | 24/120 [25:03<1:40:22, 62.73s/it]

Epoch: 23 | Train loss: 0.0206 | Train acc: 0.9986 | Test loss: 0.6494 | Test acc: 0.8305 |  F1 score: 0.8222   


 21%|██        | 25/120 [26:05<1:39:15, 62.69s/it]

Epoch: 24 | Train loss: 0.0197 | Train acc: 0.9986 | Test loss: 0.6250 | Test acc: 0.8335 |  F1 score: 0.8220   


 22%|██▏       | 26/120 [27:08<1:38:03, 62.59s/it]

Epoch: 25 | Train loss: 0.0195 | Train acc: 0.9988 | Test loss: 0.6418 | Test acc: 0.8362 |  F1 score: 0.8268   


 22%|██▎       | 27/120 [28:11<1:37:07, 62.66s/it]

Epoch: 26 | Train loss: 0.0213 | Train acc: 0.9979 | Test loss: 0.6559 | Test acc: 0.8390 |  F1 score: 0.8314   


 23%|██▎       | 28/120 [29:13<1:35:54, 62.55s/it]

Epoch: 27 | Train loss: 0.0161 | Train acc: 0.9996 | Test loss: 0.6347 | Test acc: 0.8374 |  F1 score: 0.8283   


 24%|██▍       | 29/120 [30:15<1:34:42, 62.44s/it]

Epoch: 28 | Train loss: 0.0173 | Train acc: 0.9986 | Test loss: 0.6310 | Test acc: 0.8420 |  F1 score: 0.8349   


 25%|██▌       | 30/120 [31:18<1:33:55, 62.61s/it]

Epoch: 29 | Train loss: 0.0138 | Train acc: 0.9995 | Test loss: 0.6190 | Test acc: 0.8447 |  F1 score: 0.8389   


 26%|██▌       | 31/120 [32:21<1:32:58, 62.68s/it]

Epoch: 30 | Train loss: 0.0131 | Train acc: 0.9996 | Test loss: 0.6450 | Test acc: 0.8333 |  F1 score: 0.8214   


 27%|██▋       | 32/120 [33:24<1:31:58, 62.71s/it]

Epoch: 31 | Train loss: 0.0170 | Train acc: 0.9986 | Test loss: 0.6479 | Test acc: 0.8374 |  F1 score: 0.8300   


 28%|██▊       | 33/120 [34:26<1:30:53, 62.69s/it]

Epoch: 32 | Train loss: 0.0136 | Train acc: 0.9991 | Test loss: 0.6225 | Test acc: 0.8340 |  F1 score: 0.8233   


 28%|██▊       | 34/120 [35:29<1:30:00, 62.79s/it]

Epoch: 33 | Train loss: 0.0174 | Train acc: 0.9984 | Test loss: 0.6569 | Test acc: 0.8411 |  F1 score: 0.8350   


 29%|██▉       | 35/120 [36:32<1:28:49, 62.70s/it]

Epoch: 34 | Train loss: 0.0110 | Train acc: 0.9996 | Test loss: 0.6689 | Test acc: 0.8369 |  F1 score: 0.8294   


 30%|███       | 36/120 [37:35<1:27:46, 62.70s/it]

Epoch: 35 | Train loss: 0.0151 | Train acc: 0.9991 | Test loss: 0.6594 | Test acc: 0.8377 |  F1 score: 0.8274   


 31%|███       | 37/120 [38:37<1:26:42, 62.68s/it]

Epoch: 36 | Train loss: 0.0289 | Train acc: 0.9973 | Test loss: 0.6761 | Test acc: 0.8339 |  F1 score: 0.8306   


 32%|███▏      | 38/120 [39:40<1:25:45, 62.75s/it]

Epoch: 37 | Train loss: 0.0289 | Train acc: 0.9950 | Test loss: 0.7544 | Test acc: 0.8227 |  F1 score: 0.8192   


 32%|███▎      | 39/120 [40:43<1:24:37, 62.69s/it]

Epoch: 38 | Train loss: 0.0208 | Train acc: 0.9977 | Test loss: 0.6380 | Test acc: 0.8377 |  F1 score: 0.8291   


 33%|███▎      | 40/120 [41:46<1:23:47, 62.84s/it]

Epoch: 39 | Train loss: 0.0128 | Train acc: 0.9991 | Test loss: 0.6532 | Test acc: 0.8324 |  F1 score: 0.8252   


 34%|███▍      | 41/120 [42:48<1:22:28, 62.64s/it]

Epoch: 40 | Train loss: 0.0095 | Train acc: 0.9998 | Test loss: 0.6870 | Test acc: 0.8395 |  F1 score: 0.8266   


 35%|███▌      | 42/120 [43:50<1:21:17, 62.54s/it]

Epoch: 41 | Train loss: 0.0117 | Train acc: 0.9998 | Test loss: 0.6378 | Test acc: 0.8427 |  F1 score: 0.8359   


 36%|███▌      | 43/120 [44:53<1:20:06, 62.42s/it]

Epoch: 42 | Train loss: 0.0128 | Train acc: 0.9991 | Test loss: 0.6725 | Test acc: 0.8354 |  F1 score: 0.8253   


 37%|███▋      | 44/120 [45:55<1:19:09, 62.49s/it]

Epoch: 43 | Train loss: 0.0551 | Train acc: 0.9870 | Test loss: 0.7795 | Test acc: 0.8150 |  F1 score: 0.7956   


 38%|███▊      | 45/120 [46:57<1:17:56, 62.35s/it]

Epoch: 44 | Train loss: 0.0161 | Train acc: 0.9989 | Test loss: 0.6496 | Test acc: 0.8269 |  F1 score: 0.8214   


 38%|███▊      | 46/120 [48:00<1:16:56, 62.38s/it]

Epoch: 45 | Train loss: 0.0136 | Train acc: 0.9993 | Test loss: 0.6766 | Test acc: 0.8354 |  F1 score: 0.8205   


 39%|███▉      | 47/120 [49:03<1:16:07, 62.56s/it]

Epoch: 46 | Train loss: 0.0111 | Train acc: 0.9996 | Test loss: 0.6259 | Test acc: 0.8413 |  F1 score: 0.8326   


 40%|████      | 48/120 [50:05<1:15:00, 62.51s/it]

Epoch: 47 | Train loss: 0.0091 | Train acc: 1.0000 | Test loss: 0.6279 | Test acc: 0.8425 |  F1 score: 0.8329   


 41%|████      | 49/120 [51:08<1:14:07, 62.65s/it]

Epoch: 48 | Train loss: 0.0090 | Train acc: 0.9996 | Test loss: 0.6786 | Test acc: 0.8303 |  F1 score: 0.8171   


 42%|████▏     | 50/120 [52:11<1:13:02, 62.61s/it]

Epoch: 49 | Train loss: 0.0082 | Train acc: 0.9996 | Test loss: 0.6703 | Test acc: 0.8411 |  F1 score: 0.8276   


 42%|████▎     | 51/120 [53:13<1:11:53, 62.52s/it]

Epoch: 50 | Train loss: 0.0089 | Train acc: 0.9993 | Test loss: 0.6752 | Test acc: 0.8377 |  F1 score: 0.8239   


 43%|████▎     | 52/120 [54:15<1:10:37, 62.31s/it]

Epoch: 51 | Train loss: 0.0123 | Train acc: 0.9989 | Test loss: 0.7152 | Test acc: 0.8312 |  F1 score: 0.8295   


 44%|████▍     | 53/120 [55:17<1:09:45, 62.47s/it]

Epoch: 52 | Train loss: 0.0405 | Train acc: 0.9922 | Test loss: 0.7135 | Test acc: 0.8283 |  F1 score: 0.8155   


 45%|████▌     | 54/120 [56:21<1:08:54, 62.65s/it]

Epoch: 53 | Train loss: 0.0255 | Train acc: 0.9956 | Test loss: 0.6841 | Test acc: 0.8377 |  F1 score: 0.8319   


 46%|████▌     | 55/120 [57:23<1:07:51, 62.63s/it]

Epoch: 54 | Train loss: 0.0102 | Train acc: 0.9989 | Test loss: 0.6588 | Test acc: 0.8376 |  F1 score: 0.8269   


 47%|████▋     | 56/120 [58:25<1:06:41, 62.52s/it]

Epoch: 55 | Train loss: 0.0123 | Train acc: 0.9984 | Test loss: 0.6819 | Test acc: 0.8319 |  F1 score: 0.8250   


 48%|████▊     | 57/120 [59:28<1:05:37, 62.50s/it]

Epoch: 56 | Train loss: 0.0098 | Train acc: 0.9998 | Test loss: 0.6924 | Test acc: 0.8326 |  F1 score: 0.8251   


 48%|████▊     | 58/120 [1:00:31<1:04:38, 62.55s/it]

Epoch: 57 | Train loss: 0.0080 | Train acc: 0.9998 | Test loss: 0.6637 | Test acc: 0.8328 |  F1 score: 0.8205   


 49%|████▉     | 59/120 [1:01:33<1:03:39, 62.62s/it]

Epoch: 58 | Train loss: 0.0103 | Train acc: 0.9991 | Test loss: 0.6702 | Test acc: 0.8399 |  F1 score: 0.8264   


 50%|█████     | 60/120 [1:02:36<1:02:43, 62.73s/it]

Epoch: 59 | Train loss: 0.0075 | Train acc: 0.9998 | Test loss: 0.6809 | Test acc: 0.8349 |  F1 score: 0.8278   


 51%|█████     | 61/120 [1:03:39<1:01:42, 62.76s/it]

Epoch: 60 | Train loss: 0.0070 | Train acc: 1.0000 | Test loss: 0.6683 | Test acc: 0.8392 |  F1 score: 0.8287   


 52%|█████▏    | 62/120 [1:04:42<1:00:40, 62.77s/it]

Epoch: 61 | Train loss: 0.0100 | Train acc: 0.9988 | Test loss: 0.6800 | Test acc: 0.8406 |  F1 score: 0.8310   


 52%|█████▎    | 63/120 [1:05:44<59:34, 62.71s/it]  

Epoch: 62 | Train loss: 0.0096 | Train acc: 0.9989 | Test loss: 0.6938 | Test acc: 0.8370 |  F1 score: 0.8267   


 53%|█████▎    | 64/120 [1:06:47<58:26, 62.62s/it]

Epoch: 63 | Train loss: 0.0087 | Train acc: 0.9996 | Test loss: 0.6745 | Test acc: 0.8354 |  F1 score: 0.8269   


 54%|█████▍    | 65/120 [1:07:49<57:20, 62.55s/it]

Epoch: 64 | Train loss: 0.0066 | Train acc: 0.9993 | Test loss: 0.6806 | Test acc: 0.8319 |  F1 score: 0.8224   


 55%|█████▌    | 66/120 [1:08:52<56:18, 62.57s/it]

Epoch: 65 | Train loss: 0.0078 | Train acc: 0.9996 | Test loss: 0.6636 | Test acc: 0.8377 |  F1 score: 0.8276   


 56%|█████▌    | 67/120 [1:09:55<55:22, 62.69s/it]

Epoch: 66 | Train loss: 0.0082 | Train acc: 0.9995 | Test loss: 0.7077 | Test acc: 0.8305 |  F1 score: 0.8242   


 57%|█████▋    | 68/120 [1:10:57<54:17, 62.64s/it]

Epoch: 67 | Train loss: 0.0082 | Train acc: 0.9995 | Test loss: 0.6746 | Test acc: 0.8370 |  F1 score: 0.8284   


 57%|█████▊    | 69/120 [1:12:00<53:14, 62.64s/it]

Epoch: 68 | Train loss: 0.0075 | Train acc: 1.0000 | Test loss: 0.6669 | Test acc: 0.8399 |  F1 score: 0.8311   


 58%|█████▊    | 70/120 [1:13:03<52:16, 62.73s/it]

Epoch: 69 | Train loss: 0.0062 | Train acc: 0.9998 | Test loss: 0.6687 | Test acc: 0.8420 |  F1 score: 0.8334   


 59%|█████▉    | 71/120 [1:14:05<51:01, 62.47s/it]

Epoch: 70 | Train loss: 0.0068 | Train acc: 0.9998 | Test loss: 0.6820 | Test acc: 0.8440 |  F1 score: 0.8336   


 60%|██████    | 72/120 [1:15:08<50:03, 62.56s/it]

Epoch: 71 | Train loss: 0.0059 | Train acc: 1.0000 | Test loss: 0.6581 | Test acc: 0.8441 |  F1 score: 0.8361   


 61%|██████    | 73/120 [1:16:10<49:00, 62.56s/it]

Epoch: 72 | Train loss: 0.0085 | Train acc: 0.9988 | Test loss: 0.6609 | Test acc: 0.8392 |  F1 score: 0.8283   


 62%|██████▏   | 74/120 [1:17:12<47:52, 62.45s/it]

Epoch: 73 | Train loss: 0.0194 | Train acc: 0.9964 | Test loss: 0.6903 | Test acc: 0.8362 |  F1 score: 0.8253   


 62%|██████▎   | 75/120 [1:18:15<46:56, 62.59s/it]

Epoch: 74 | Train loss: 0.0087 | Train acc: 0.9989 | Test loss: 0.7011 | Test acc: 0.8399 |  F1 score: 0.8324   


 63%|██████▎   | 76/120 [1:19:18<45:55, 62.62s/it]

Epoch: 75 | Train loss: 0.0071 | Train acc: 0.9998 | Test loss: 0.6786 | Test acc: 0.8356 |  F1 score: 0.8249   


 64%|██████▍   | 77/120 [1:20:21<44:54, 62.67s/it]

Epoch: 76 | Train loss: 0.0078 | Train acc: 0.9991 | Test loss: 0.6859 | Test acc: 0.8383 |  F1 score: 0.8308   


 65%|██████▌   | 78/120 [1:21:24<43:58, 62.83s/it]

Epoch: 77 | Train loss: 0.0192 | Train acc: 0.9964 | Test loss: 0.6799 | Test acc: 0.8466 |  F1 score: 0.8448   


 66%|██████▌   | 79/120 [1:22:27<43:00, 62.94s/it]

Epoch: 78 | Train loss: 0.0074 | Train acc: 0.9996 | Test loss: 0.6653 | Test acc: 0.8404 |  F1 score: 0.8351   


 67%|██████▋   | 80/120 [1:23:30<42:01, 63.03s/it]

Epoch: 79 | Train loss: 0.0060 | Train acc: 0.9998 | Test loss: 0.6629 | Test acc: 0.8441 |  F1 score: 0.8324   


 68%|██████▊   | 81/120 [1:24:33<40:49, 62.80s/it]

Epoch: 80 | Train loss: 0.0057 | Train acc: 1.0000 | Test loss: 0.6232 | Test acc: 0.8470 |  F1 score: 0.8399   


 68%|██████▊   | 82/120 [1:25:34<39:34, 62.49s/it]

Epoch: 81 | Train loss: 0.0060 | Train acc: 0.9998 | Test loss: 0.6567 | Test acc: 0.8468 |  F1 score: 0.8402   


 69%|██████▉   | 83/120 [1:26:37<38:32, 62.49s/it]

Epoch: 82 | Train loss: 0.0048 | Train acc: 1.0000 | Test loss: 0.6435 | Test acc: 0.8447 |  F1 score: 0.8378   


 70%|███████   | 84/120 [1:27:39<37:26, 62.39s/it]

Epoch: 83 | Train loss: 0.0047 | Train acc: 1.0000 | Test loss: 0.6622 | Test acc: 0.8468 |  F1 score: 0.8383   


 71%|███████   | 85/120 [1:28:41<36:18, 62.25s/it]

Epoch: 84 | Train loss: 0.0045 | Train acc: 1.0000 | Test loss: 0.6491 | Test acc: 0.8454 |  F1 score: 0.8363   


 72%|███████▏  | 86/120 [1:29:43<35:17, 62.28s/it]

Epoch: 85 | Train loss: 0.0044 | Train acc: 1.0000 | Test loss: 0.6449 | Test acc: 0.8504 |  F1 score: 0.8437   


 72%|███████▎  | 87/120 [1:30:46<34:14, 62.24s/it]

Epoch: 86 | Train loss: 0.0055 | Train acc: 0.9998 | Test loss: 0.6635 | Test acc: 0.8433 |  F1 score: 0.8322   


 73%|███████▎  | 88/120 [1:31:48<33:11, 62.24s/it]

Epoch: 87 | Train loss: 0.0042 | Train acc: 1.0000 | Test loss: 0.6964 | Test acc: 0.8454 |  F1 score: 0.8317   


 74%|███████▍  | 89/120 [1:32:51<32:15, 62.45s/it]

Epoch: 88 | Train loss: 0.0054 | Train acc: 0.9996 | Test loss: 0.6610 | Test acc: 0.8420 |  F1 score: 0.8332   


 75%|███████▌  | 90/120 [1:33:53<31:15, 62.50s/it]

Epoch: 89 | Train loss: 0.0046 | Train acc: 1.0000 | Test loss: 0.6774 | Test acc: 0.8417 |  F1 score: 0.8384   


 76%|███████▌  | 91/120 [1:34:56<30:14, 62.57s/it]

Epoch: 90 | Train loss: 0.0053 | Train acc: 0.9998 | Test loss: 0.6690 | Test acc: 0.8461 |  F1 score: 0.8344   


 77%|███████▋  | 92/120 [1:35:59<29:12, 62.60s/it]

Epoch: 91 | Train loss: 0.0040 | Train acc: 1.0000 | Test loss: 0.6670 | Test acc: 0.8454 |  F1 score: 0.8373   


 78%|███████▊  | 93/120 [1:37:01<28:05, 62.43s/it]

Epoch: 92 | Train loss: 0.0039 | Train acc: 1.0000 | Test loss: 0.6651 | Test acc: 0.8482 |  F1 score: 0.8379   


 78%|███████▊  | 94/120 [1:38:04<27:08, 62.64s/it]

Epoch: 93 | Train loss: 0.0042 | Train acc: 0.9998 | Test loss: 0.6750 | Test acc: 0.8497 |  F1 score: 0.8387   


 79%|███████▉  | 95/120 [1:39:07<26:08, 62.75s/it]

Epoch: 94 | Train loss: 0.0038 | Train acc: 1.0000 | Test loss: 0.6708 | Test acc: 0.8461 |  F1 score: 0.8365   


 80%|████████  | 96/120 [1:40:10<25:07, 62.80s/it]

Epoch: 95 | Train loss: 0.0037 | Train acc: 1.0000 | Test loss: 0.6724 | Test acc: 0.8454 |  F1 score: 0.8368   


 81%|████████  | 97/120 [1:41:12<24:03, 62.74s/it]

Epoch: 96 | Train loss: 0.0048 | Train acc: 1.0000 | Test loss: 0.6815 | Test acc: 0.8468 |  F1 score: 0.8394   


 82%|████████▏ | 98/120 [1:42:15<22:57, 62.62s/it]

Epoch: 97 | Train loss: 0.0038 | Train acc: 1.0000 | Test loss: 0.7001 | Test acc: 0.8411 |  F1 score: 0.8273   


 82%|████████▎ | 99/120 [1:43:17<21:53, 62.52s/it]

Epoch: 98 | Train loss: 0.0041 | Train acc: 1.0000 | Test loss: 0.6587 | Test acc: 0.8438 |  F1 score: 0.8359   


 83%|████████▎ | 100/120 [1:44:19<20:49, 62.46s/it]

Epoch: 99 | Train loss: 0.0167 | Train acc: 0.9979 | Test loss: 0.6815 | Test acc: 0.8411 |  F1 score: 0.8310   


 84%|████████▍ | 101/120 [1:45:23<19:51, 62.68s/it]

Epoch: 100 | Train loss: 0.0159 | Train acc: 0.9961 | Test loss: 0.7209 | Test acc: 0.8354 |  F1 score: 0.8210   


 85%|████████▌ | 102/120 [1:46:26<18:49, 62.77s/it]

Epoch: 101 | Train loss: 0.0223 | Train acc: 0.9941 | Test loss: 0.6746 | Test acc: 0.8333 |  F1 score: 0.8248   


 86%|████████▌ | 103/120 [1:47:28<17:44, 62.59s/it]

Epoch: 102 | Train loss: 0.0206 | Train acc: 0.9947 | Test loss: 0.6766 | Test acc: 0.8461 |  F1 score: 0.8407   


 87%|████████▋ | 104/120 [1:48:30<16:39, 62.44s/it]

Epoch: 103 | Train loss: 0.0241 | Train acc: 0.9963 | Test loss: 0.8007 | Test acc: 0.8252 |  F1 score: 0.8188   


 88%|████████▊ | 105/120 [1:49:33<15:38, 62.59s/it]

Epoch: 104 | Train loss: 0.0091 | Train acc: 0.9988 | Test loss: 0.6778 | Test acc: 0.8369 |  F1 score: 0.8275   


 88%|████████▊ | 106/120 [1:50:36<14:38, 62.75s/it]

Epoch: 105 | Train loss: 0.0128 | Train acc: 0.9979 | Test loss: 0.7114 | Test acc: 0.8422 |  F1 score: 0.8363   


 89%|████████▉ | 107/120 [1:51:39<13:37, 62.92s/it]

Epoch: 106 | Train loss: 0.0096 | Train acc: 0.9989 | Test loss: 0.6732 | Test acc: 0.8356 |  F1 score: 0.8243   


 90%|█████████ | 108/120 [1:52:42<12:34, 62.90s/it]

Epoch: 107 | Train loss: 0.0068 | Train acc: 1.0000 | Test loss: 0.7083 | Test acc: 0.8392 |  F1 score: 0.8312   


 91%|█████████ | 109/120 [1:53:45<11:32, 63.00s/it]

Epoch: 108 | Train loss: 0.0063 | Train acc: 0.9993 | Test loss: 0.7041 | Test acc: 0.8376 |  F1 score: 0.8279   


 92%|█████████▏| 110/120 [1:54:48<10:28, 62.85s/it]

Epoch: 109 | Train loss: 0.0076 | Train acc: 0.9996 | Test loss: 0.6986 | Test acc: 0.8397 |  F1 score: 0.8308   


 92%|█████████▎| 111/120 [1:55:51<09:25, 62.89s/it]

Epoch: 110 | Train loss: 0.0072 | Train acc: 0.9993 | Test loss: 0.6718 | Test acc: 0.8376 |  F1 score: 0.8311   


 93%|█████████▎| 112/120 [1:56:54<08:23, 62.94s/it]

Epoch: 111 | Train loss: 0.0143 | Train acc: 0.9975 | Test loss: 0.7044 | Test acc: 0.8370 |  F1 score: 0.8271   


 94%|█████████▍| 113/120 [1:57:57<07:20, 62.91s/it]

Epoch: 112 | Train loss: 0.0061 | Train acc: 0.9996 | Test loss: 0.6766 | Test acc: 0.8397 |  F1 score: 0.8316   


 95%|█████████▌| 114/120 [1:58:59<06:15, 62.66s/it]

Epoch: 113 | Train loss: 0.0049 | Train acc: 1.0000 | Test loss: 0.6814 | Test acc: 0.8342 |  F1 score: 0.8215   


 96%|█████████▌| 115/120 [2:00:02<05:13, 62.78s/it]

Epoch: 114 | Train loss: 0.0050 | Train acc: 0.9996 | Test loss: 0.6593 | Test acc: 0.8370 |  F1 score: 0.8260   


 97%|█████████▋| 116/120 [2:01:05<04:11, 62.83s/it]

Epoch: 115 | Train loss: 0.0038 | Train acc: 1.0000 | Test loss: 0.6624 | Test acc: 0.8427 |  F1 score: 0.8336   


 98%|█████████▊| 117/120 [2:02:08<03:08, 62.89s/it]

Epoch: 116 | Train loss: 0.0035 | Train acc: 1.0000 | Test loss: 0.6581 | Test acc: 0.8406 |  F1 score: 0.8312   


 98%|█████████▊| 118/120 [2:03:11<02:06, 63.01s/it]

Epoch: 117 | Train loss: 0.0042 | Train acc: 0.9998 | Test loss: 0.6730 | Test acc: 0.8404 |  F1 score: 0.8301   


 99%|█████████▉| 119/120 [2:04:14<01:02, 62.98s/it]

Epoch: 118 | Train loss: 0.0039 | Train acc: 1.0000 | Test loss: 0.6627 | Test acc: 0.8418 |  F1 score: 0.8317   


100%|██████████| 120/120 [2:05:17<00:00, 62.64s/it]

Epoch: 119 | Train loss: 0.0037 | Train acc: 1.0000 | Test loss: 0.6664 | Test acc: 0.8475 |  F1 score: 0.8382   
the best test acc is :0.8179
Total training time: 7517.327 seconds


In [ ]:
import torchvision.models as models

model_preTrained_Resnet50 = models.resnet50(pretrained=True)     # 使用內建的 model 


# optimizer = torch.optim.SGD(model_preTrained_Resnet50.parameters(), lr = 0.001) # 選擇你想用的 optimizer
optimizer = torch.optim.SGD(model_preTrained_Resnet50.parameters(), lr = 0.001, momentum=0.9) # 選擇你想用的 optimizer

# optimizer = torch.optim.Adam(model_Resnet50.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 


# change fully connected layer to 7
num_ftrs = model_preTrained_Resnet50.fc.in_features
model_preTrained_Resnet50.fc = nn.Linear(num_ftrs, 7)

# device setting
model_preTrained_Resnet50 = model_preTrained_Resnet50.to(device)

# Start the timer
from timeit import default_timer as timer
start_time = timer()

# Train model_0
model_VGG_results = train(model=model_preTrained_Resnet50,
              train_dataloader=train_data_loader_224,
              test_dataloader=test_data_loader_224,
              optimizer=optimizer,
              loss_fn=loss_fn,
              best_model_name="best_model_pretrain_Resnet50_7.pth",
              epochs=40)

# End the timer and print out how long it took
end_time = timer()
print(f"Total training time: {end_time-start_time:.3f} seconds")

c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  2%|▎         | 1/40 [01:24<55:11, 84.91s/it]

Epoch: 0 | Train loss: 1.3020 | Train acc: 0.6268 | Test loss: 0.9094 | Test acc: 0.7448 |  F1 score: 0.7212   


  5%|▌         | 2/40 [02:50<53:50, 85.02s/it]

Epoch: 1 | Train loss: 0.7284 | Train acc: 0.7907 | Test loss: 0.7710 | Test acc: 0.7575 |  F1 score: 0.7368   


  8%|▊         | 3/40 [04:14<52:24, 85.00s/it]

Epoch: 2 | Train loss: 0.4988 | Train acc: 0.8478 | Test loss: 0.8098 | Test acc: 0.7440 |  F1 score: 0.6798   


 10%|█         | 4/40 [05:39<51:00, 85.00s/it]

Epoch: 3 | Train loss: 0.3688 | Train acc: 0.8899 | Test loss: 0.6763 | Test acc: 0.7794 |  F1 score: 0.7789   


 12%|█▎        | 5/40 [07:05<49:36, 85.04s/it]

Epoch: 4 | Train loss: 0.2559 | Train acc: 0.9295 | Test loss: 0.6906 | Test acc: 0.7893 |  F1 score: 0.7600   


 15%|█▌        | 6/40 [08:30<48:10, 85.00s/it]

Epoch: 5 | Train loss: 0.1652 | Train acc: 0.9595 | Test loss: 0.6386 | Test acc: 0.8083 |  F1 score: 0.8038   


 18%|█▊        | 7/40 [09:54<46:44, 84.98s/it]

Epoch: 6 | Train loss: 0.1035 | Train acc: 0.9798 | Test loss: 0.5708 | Test acc: 0.8309 |  F1 score: 0.8225   


 20%|██        | 8/40 [11:20<45:20, 85.02s/it]

Epoch: 7 | Train loss: 0.0842 | Train acc: 0.9835 | Test loss: 0.6027 | Test acc: 0.8282 |  F1 score: 0.8219   


 22%|██▎       | 9/40 [12:45<43:55, 85.02s/it]

Epoch: 8 | Train loss: 0.0884 | Train acc: 0.9822 | Test loss: 0.6671 | Test acc: 0.8158 |  F1 score: 0.8034   


 25%|██▌       | 10/40 [14:10<42:33, 85.12s/it]

Epoch: 9 | Train loss: 0.0823 | Train acc: 0.9815 | Test loss: 0.6357 | Test acc: 0.8236 |  F1 score: 0.8146   


 28%|██▊       | 11/40 [15:36<41:12, 85.26s/it]

Epoch: 10 | Train loss: 0.0633 | Train acc: 0.9874 | Test loss: 0.6766 | Test acc: 0.8151 |  F1 score: 0.7999   


 30%|███       | 12/40 [17:01<39:46, 85.25s/it]

Epoch: 11 | Train loss: 0.0372 | Train acc: 0.9954 | Test loss: 0.5900 | Test acc: 0.8303 |  F1 score: 0.8249   


 32%|███▎      | 13/40 [18:26<38:23, 85.30s/it]

Epoch: 12 | Train loss: 0.0325 | Train acc: 0.9956 | Test loss: 0.6702 | Test acc: 0.8257 |  F1 score: 0.8156   


 35%|███▌      | 14/40 [19:51<36:57, 85.28s/it]

Epoch: 13 | Train loss: 0.0257 | Train acc: 0.9973 | Test loss: 0.5764 | Test acc: 0.8324 |  F1 score: 0.8281   


 38%|███▊      | 15/40 [21:17<35:31, 85.28s/it]

Epoch: 14 | Train loss: 0.0251 | Train acc: 0.9968 | Test loss: 0.6944 | Test acc: 0.8260 |  F1 score: 0.8124   


 40%|████      | 16/40 [22:42<34:03, 85.16s/it]

Epoch: 15 | Train loss: 0.0386 | Train acc: 0.9915 | Test loss: 0.7982 | Test acc: 0.8080 |  F1 score: 0.7897   


 42%|████▎     | 17/40 [24:06<32:37, 85.10s/it]

Epoch: 16 | Train loss: 0.0576 | Train acc: 0.9879 | Test loss: 0.6653 | Test acc: 0.8280 |  F1 score: 0.8252   


 45%|████▌     | 18/40 [25:32<31:13, 85.14s/it]

Epoch: 17 | Train loss: 0.0290 | Train acc: 0.9961 | Test loss: 0.6041 | Test acc: 0.8394 |  F1 score: 0.8393   


 48%|████▊     | 19/40 [26:57<29:45, 85.05s/it]

Epoch: 18 | Train loss: 0.0320 | Train acc: 0.9933 | Test loss: 0.6434 | Test acc: 0.8360 |  F1 score: 0.8290   


 50%|█████     | 20/40 [28:22<28:20, 85.03s/it]

Epoch: 19 | Train loss: 0.0270 | Train acc: 0.9956 | Test loss: 0.6118 | Test acc: 0.8317 |  F1 score: 0.8298   


 52%|█████▎    | 21/40 [29:46<26:55, 85.00s/it]

Epoch: 20 | Train loss: 0.0228 | Train acc: 0.9961 | Test loss: 0.6754 | Test acc: 0.8337 |  F1 score: 0.8271   


 55%|█████▌    | 22/40 [31:12<25:31, 85.06s/it]

Epoch: 21 | Train loss: 0.0149 | Train acc: 0.9984 | Test loss: 0.5824 | Test acc: 0.8516 |  F1 score: 0.8444   


 57%|█████▊    | 23/40 [32:37<24:06, 85.09s/it]

Epoch: 22 | Train loss: 0.0126 | Train acc: 0.9988 | Test loss: 0.5800 | Test acc: 0.8545 |  F1 score: 0.8493   


 60%|██████    | 24/40 [34:02<22:42, 85.15s/it]

Epoch: 23 | Train loss: 0.0176 | Train acc: 0.9979 | Test loss: 0.5998 | Test acc: 0.8470 |  F1 score: 0.8421   


 62%|██████▎   | 25/40 [35:27<21:16, 85.11s/it]

Epoch: 24 | Train loss: 0.0171 | Train acc: 0.9977 | Test loss: 0.6537 | Test acc: 0.8403 |  F1 score: 0.8299   


 65%|██████▌   | 26/40 [36:52<19:51, 85.08s/it]

Epoch: 25 | Train loss: 0.0112 | Train acc: 0.9991 | Test loss: 0.6083 | Test acc: 0.8472 |  F1 score: 0.8367   


 68%|██████▊   | 27/40 [38:17<18:25, 85.04s/it]

Epoch: 26 | Train loss: 0.0118 | Train acc: 0.9988 | Test loss: 0.6400 | Test acc: 0.8413 |  F1 score: 0.8353   


 70%|███████   | 28/40 [39:42<16:59, 85.00s/it]

Epoch: 27 | Train loss: 0.0199 | Train acc: 0.9963 | Test loss: 0.6713 | Test acc: 0.8314 |  F1 score: 0.8263   


 72%|███████▎  | 29/40 [41:07<15:34, 84.97s/it]

Epoch: 28 | Train loss: 0.0338 | Train acc: 0.9927 | Test loss: 0.6311 | Test acc: 0.8421 |  F1 score: 0.8353   


 75%|███████▌  | 30/40 [42:32<14:10, 85.04s/it]

Epoch: 29 | Train loss: 0.0158 | Train acc: 0.9972 | Test loss: 0.5976 | Test acc: 0.8545 |  F1 score: 0.8473   


 78%|███████▊  | 31/40 [43:57<12:45, 85.09s/it]

Epoch: 30 | Train loss: 0.0104 | Train acc: 0.9995 | Test loss: 0.5829 | Test acc: 0.8541 |  F1 score: 0.8468   


 80%|████████  | 32/40 [45:23<11:21, 85.19s/it]

Epoch: 31 | Train loss: 0.0137 | Train acc: 0.9984 | Test loss: 0.6153 | Test acc: 0.8484 |  F1 score: 0.8426   


 82%|████████▎ | 33/40 [46:48<09:56, 85.19s/it]

Epoch: 32 | Train loss: 0.0111 | Train acc: 0.9989 | Test loss: 0.5893 | Test acc: 0.8506 |  F1 score: 0.8459   


 85%|████████▌ | 34/40 [48:13<08:30, 85.14s/it]

Epoch: 33 | Train loss: 0.0234 | Train acc: 0.9961 | Test loss: 0.6423 | Test acc: 0.8421 |  F1 score: 0.8344   


 88%|████████▊ | 35/40 [49:38<07:05, 85.17s/it]

Epoch: 34 | Train loss: 0.0127 | Train acc: 0.9982 | Test loss: 0.6354 | Test acc: 0.8383 |  F1 score: 0.8313   


 90%|█████████ | 36/40 [51:04<05:41, 85.31s/it]

Epoch: 35 | Train loss: 0.0106 | Train acc: 0.9991 | Test loss: 0.6574 | Test acc: 0.8408 |  F1 score: 0.8289   


 92%|█████████▎| 37/40 [52:29<04:15, 85.30s/it]

Epoch: 36 | Train loss: 0.0107 | Train acc: 0.9986 | Test loss: 0.6123 | Test acc: 0.8483 |  F1 score: 0.8414   


 95%|█████████▌| 38/40 [53:54<02:50, 85.25s/it]

Epoch: 37 | Train loss: 0.0160 | Train acc: 0.9968 | Test loss: 0.6162 | Test acc: 0.8428 |  F1 score: 0.8387   


 98%|█████████▊| 39/40 [55:19<01:25, 85.23s/it]

Epoch: 38 | Train loss: 0.0212 | Train acc: 0.9957 | Test loss: 0.5908 | Test acc: 0.8523 |  F1 score: 0.8461   


100%|██████████| 40/40 [56:44<00:00, 85.12s/it]

Epoch: 39 | Train loss: 0.0086 | Train acc: 0.9993 | Test loss: 0.5775 | Test acc: 0.8559 |  F1 score: 0.8506   
the best test acc is :0.8309
Total training time: 3404.949 seconds


# model output

In [ ]:
import torchvision.models as models

new_load_model = models.resnet18(pretrained=True)     # 使用內建的 model 

optimizer = torch.optim.SGD(new_load_model.parameters(), lr = 0.001) # 選擇你想用的 optimizer
# optimizer = torch.optim.Adam(model_VGG16.parameters(), lr =0.01)

# Loss function
loss_fn = nn.CrossEntropyLoss()                # 選擇想用的 loss functionmodel_vgg16 = 




# VGG16 setting
# =============
# # 获取分类器中最后一个全连接层之前的部分
# classifier = list(new_load_VGG16.classifier.children())[:-1]

# # 移除原始模型的最后一个全连接层
# # 并添加一个新的全连接层，输出特征数为 7
# classifier.append(torch.nn.Linear(4096, 7))

# # 替换原始模型的分类器
# new_load_VGG16.classifier = torch.nn.Sequential(*classifier)

# ============

# resnet setting
#  ============
# change fully connected layer to 7
num_ftrs = new_load_model.fc.in_features
new_load_model.fc = nn.Linear(num_ftrs, 7)
#  ============


new_load_model =  new_load_model.to(device)

new_load_model.load_state_dict(torch.load("./best_model_pretrain_Resnet18_7.pth", map_location=device))

from torchinfo import summary

# summary(model_preTrained_VGG16_7, input_size=[1,3,224,224])





# Start the timer
from timeit import default_timer as timer
start_time = timer()

new_load_model.eval()

loss, acc, f1 = test_step(new_load_model,
                        loss_fn=loss_fn,
                        dataloader=test_data_loader_224,
                        device=device)

print("acc:{:.4f}".format(acc))
print("f1:{:.4f}".format(f1))



c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\E\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


acc:0.8312
f1:0.8258


In [ ]:
print(loss)
print("acc:{:.4f}".format(acc))
print("f1:{:.4f}".format(f1))


0.6782166653058745
acc:0.7466
f1:0.7649


In [ ]:
# image_path = "./HAM10000/images/ISIC_0024306.jpg"

# def img2tensor(img_path):
#     img = cv2.imread(img_path)
#     img = cv2.resize(img, (224, 224))

#     data = torch.from_numpy(img).permute(2, 0, 1).unsqueeze(0).float() / 255.0
#     return data

# def flattenTensor(tensor):
#     tensor = torch.squeeze(tensor)
#     flatted_tensor = tensor.view(-1)
#     return flatted_tensor

# # output = conv_layer(input_data)
# # print(input_data.shape)
# # print(output.shape)

# # output = conv_block(input_data)
# # output = conv_block_2(output)
# input_data = img2tensor(image_path)
# input_data = input_data.to(device)

# model_VGG16.eval()
# with torch.no_grad():
#     output = model_VGG16(input_data)
# prob = torch.softmax(output, dim=1)
# print(input_data.shape)
# print(output.shape)
# print(prob)
# print(flattenTensor(output).shape)

In [ ]:
# import os
# import csv
# import time

# input_folder = "HAM10000/images/"
# csvfile_name = "./img_conv3.csv"


# res = []

# # open every img
# start = time.time()
# for filename in os.listdir(input_folder):

#     image_path  = os.path.join(input_folder, filename)
#     # print(image_path)
#     img = img2tensor(image_path)
#     tensor = conv3(img)
#     tensor = flattenTensor(tensor)
#     vec = tensor.tolist()

#     vec = [filename] + vec
#     res.append(vec)
# end = time.time()

# print("time cost : {}".format(end - start))

# # print(res)
# with open(csvfile_name, 'w', newline='', encoding='utf-8') as csvfile:
#     # try:
#     csvwriter = csv.writer(csvfile)
#     csvwriter.writerows(res)
#     # except Exception as e:
#     #     logging.error("csv error : %s" , e)
#     #     print('csv encoding error')

## Tiny VGG

input wiil be [3, 64, 64]

In [ ]:
# # Set random seeds

# torch.manual_seed(42)
# torch.cuda.manual_seed(42)

# # Set number of epochs
# NUM_EPOCHS = 30

# # Recreate an instance of TinyVGG
# model_0 = TinyVGG(input_shape=3, # numbers of color channels
#           hidden_units=10,
#           output_shape=7).to(device)

# # Setup loss function and optimizer
# loss_fn = nn.CrossEntropyLoss()
# optimizer = torch.optim.Adam(params=model_0.parameters(),
#                 lr =0.001)

# # Start the timer
# from timeit import default_timer as timer
# start_time = timer()

# # Train model_0
# model_0_results = train(model=model_0,
#               train_dataloader=train_data_loader,
#               test_dataloader=test_data_loader,
#               optimizer=optimizer,
#               loss_fn=loss_fn,
#               epochs=NUM_EPOCHS)

# # End the timer and print out how long it took
# end_time = timer()
# print(f"Total training time: {end_time-start_time:.3f} seconds")


 83%|████████▎ | 25/30 [25:30<05:04, 60.83s/it]
Epoch: 24 | Train loss: 0.5824 | Train acc: 0.7830 | Test loss: 0.8261 | Test acc: 0.7118  
 87%|████████▋ | 26/30 [26:31<04:03, 60.86s/it]
Epoch: 25 | Train loss: 0.5774 | Train acc: 0.7839 | Test loss: 0.8404 | Test acc: 0.7162  
 90%|█████████ | 27/30 [27:32<03:02, 60.86s/it]
Epoch: 26 | Train loss: 0.5776 | Train acc: 0.7862 | Test loss: 0.8416 | Test acc: 0.7101  
 93%|█████████▎| 28/30 [28:33<02:01, 60.82s/it]
Epoch: 27 | Train loss: 0.5675 | Train acc: 0.7873 | Test loss: 0.8176 | Test acc: 0.7065  
 97%|█████████▋| 29/30 [29:34<01:00, 60.79s/it]
Epoch: 28 | Train loss: 0.5592 | Train acc: 0.7901 | Test loss: 0.8350 | Test acc: 0.7147  
100%|██████████| 30/30 [30:35<00:00, 61.17s/it]
Epoch: 29 | Train loss: 0.5536 | Train acc: 0.7954 | Test loss: 0.8560 | Test acc: 0.7035  
Total training time: 1835.003 seconds
